//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACMADM
    {
        public string MemoNumber { get; set; }
        public string AirlineCode { get; set; }
        public string CheckDigit { get; set; }
        public Nullable<System.DateTime> MemoIssueDate { get; set; }
        public string ReportingPeriod { get; set; }
        public string AirlineContactName { get; set; }
        public string AirlineContactTelNo { get; set; }
        public string AirlineContactEmailAdd { get; set; }
        public string AgentCode { get; set; }
        public Nullable<System.DateTime> TicketDateOfIssue { get; set; }
        public string PassengerName { get; set; }
        public byte[] ReasonForMemo { get; set; }
        public string CurrencyCode { get; set; }
        public string MemoType { get; set; }
        public Nullable<decimal> AirlineCalFare { get; set; }
        public Nullable<decimal> AgentCalFare { get; set; }
        public Nullable<decimal> FareDiff { get; set; }
        public Nullable<decimal> AirlineCalTax { get; set; }
        public Nullable<decimal> AgentCalTax { get; set; }
        public Nullable<decimal> TaxDiff { get; set; }
        public Nullable<decimal> AirlineCalComm1 { get; set; }
        public Nullable<decimal> AgentCalComm1 { get; set; }
        public Nullable<decimal> Comm1Diff { get; set; }
        public Nullable<decimal> AirlineCalComm2 { get; set; }
        public Nullable<decimal> AgentCalComm2 { get; set; }
        public Nullable<decimal> Comm2Diff { get; set; }
        public Nullable<decimal> AirlineCalComm3 { get; set; }
        public Nullable<decimal> AgentCalComm3 { get; set; }
        public Nullable<decimal> Comm3Diff { get; set; }
        public Nullable<decimal> AirlineCalComm4 { get; set; }
        public Nullable<decimal> AgentCalComm4 { get; set; }
        public Nullable<decimal> Comm4Diff { get; set; }
        public Nullable<decimal> AirlineCalTotal { get; set; }
        public Nullable<decimal> AgentCalTotal { get; set; }
        public Nullable<decimal> TotalDiff { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string TaxCode1 { get; set; }
        public Nullable<decimal> TaxAmount1 { get; set; }
        public string TaxCode2 { get; set; }
        public Nullable<decimal> TaxAmount2 { get; set; }
        public string TaxCode3 { get; set; }
        public Nullable<decimal> TaxAmount3 { get; set; }
        public string TaxCode4 { get; set; }
        public Nullable<decimal> TaxAmount4 { get; set; }
        public string TaxCode5 { get; set; }
        public Nullable<decimal> TaxAmount5 { get; set; }
        public string TaxCode6 { get; set; }
        public Nullable<decimal> TaxAmount6 { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public string ReferenceNo { get; set; }
        public string ADMACM { get; set; }
    }
}
