//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjAnaDocumentCoupon
    {
        public System.Guid AdjAnaCouponGuid { get; set; }
        public Nullable<System.Guid> AdjAnaHeaderGuid { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string CouponStatus { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
    }
}
