//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_Own_MD
    {
        public string MD { get; set; }
        public string IATA { get; set; }
        public string LIBELLE { get; set; }
        public string PAYS { get; set; }
        public string TYPE { get; set; }
        public string RETRAIT { get; set; }
        public string REMARQUES { get; set; }
        public string CODE_PAYS { get; set; }
    }
}
