//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementApplicabilityAuditParameter
    {
        public int AuditCheckID { get; set; }
        public string AuditCheckName { get; set; }
        public string AuditCheckDescription { get; set; }
        public string SPToExecute { get; set; }
        public string SPMessageToExecute { get; set; }
        public string ReportAttachment { get; set; }
        public string NotificationSubject { get; set; }
        public string NotificationMessage { get; set; }
        public string NotificationRecipientList { get; set; }
        public string NotificationRecipientCCList { get; set; }
        public string NotificationRecipientBCCList { get; set; }
    }
}
