//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airlines_ICH
    {
        public string AirlineCode { get; set; }
        public string AirlineID { get; set; }
        public string AirlineName { get; set; }
        public string Zone { get; set; }
        public string Status { get; set; }
        public string Category { get; set; }
    }
}
