//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public string AirlineCode { get; set; }
        public string AirlineID { get; set; }
        public string AirlineName { get; set; }
        public string Zone { get; set; }
        public string Status { get; set; }
        public string Category { get; set; }
        public string AddressL1 { get; set; }
        public string AddressL2 { get; set; }
        public string AddressL3 { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public string ICHMember { get; set; }
        public string SettlementMethod { get; set; }
        public string TaxRegistrationID { get; set; }
        public string AdditionalTaxRegistrationID { get; set; }
        public string CompanyRegistrationID { get; set; }
    }
}
