//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ama25_AgentBookingAndTicketingID
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string AmaDate { get; set; }
        public string Seq { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string CheckDigits { get; set; }
        public string BookingAgent { get; set; }
        public string SignCode { get; set; }
        public string TicketingAgent { get; set; }
    }
}
