//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicableTFC
    {
        public long ID { get; set; }
        public string FromSector { get; set; }
        public string ToSector { get; set; }
        public string TaxCode { get; set; }
        public string TaxName { get; set; }
        public Nullable<System.DateTime> Effective { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public string RATDCurrency { get; set; }
        public Nullable<System.DateTime> Sale { get; set; }
        public string RATDDetails { get; set; }
        public Nullable<System.DateTime> Travel { get; set; }
        public string ExemptionsCode { get; set; }
        public Nullable<System.DateTime> ExemptionEffective { get; set; }
        public string ExemptionsDetail { get; set; }
        public string DomesticInternational { get; set; }
    }
}
