//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKERRATE
    {
        public string CurrCode { get; set; }
        public string CurrCountry { get; set; }
        public string Buying { get; set; }
        public string Selling { get; set; }
        public string CentralBank_Buying { get; set; }
        public string CentralBank_Selling { get; set; }
        public string DateUpdated { get; set; }
        public string TimeUpdated { get; set; }
        public string IND { get; set; }
        public string DATED { get; set; }
    }
}
