//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingMemo
    {
        public System.Guid BillingGuid { get; set; }
        public long OrganizationID { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceDate { get; set; }
        public string CurrencyCode { get; set; }
        public string ClearanceCurrencyCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string SettlementMonthPeriod { get; set; }
        public string SettlementMethod { get; set; }
        public string DetailNumber { get; set; }
        public string BatchSequenceNumber { get; set; }
        public string RecordWithinBatchSequence { get; set; }
        public decimal GrossBilled { get; set; }
        public decimal TotalNetAmount { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public string BillingMemoNumber { get; set; }
        public string ReasonCode { get; set; }
        public string ReasonDescription { get; set; }
        public string YourInvoiceNumber { get; set; }
        public string YourInvoiceBillingDate { get; set; }
        public Nullable<byte> Processed { get; set; }
        public Nullable<System.Guid> UploadGuid { get; set; }
    }
}
