//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bks24_DocumentIdentification1
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public string CouponUseIndicator { get; set; }
        public string ConjunctionTicketIndicator { get; set; }
        public string AgentNumericCode { get; set; }
        public string ReasonforIssuanceCode { get; set; }
        public string TourCode { get; set; }
        public string TransactionCode { get; set; }
        public string TrueOriginDestinationCityCodes { get; set; }
        public string PNRReferenceandorAirlineData { get; set; }
        public string TimeofIssue { get; set; }
        public string Reserved { get; set; }
    }
}
