//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bks30_DocumentAmount
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string Check_Digit { get; set; }
        public string CommissionableAmount { get; set; }
        public string NetFareAmount { get; set; }
        public string ReservedSpace1 { get; set; }
        public string TaxMiscellaneousFeeType1 { get; set; }
        public string TaxMiscellaneousFeeAmount1 { get; set; }
        public string TaxMiscellaneousFeeType2 { get; set; }
        public string TaxMiscellaneousFeeAmount2 { get; set; }
        public string TicketDocumentAmount { get; set; }
        public string LateReportingPenalty { get; set; }
        public string ReservedSpace { get; set; }
        public string CurrencyType { get; set; }
        public string ReservedSpace2 { get; set; }
    }
}
