//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bkt06_TransactionHeader1
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string TransactionNumber { get; set; }
        public string NetReportingIndicator { get; set; }
        public string TransactionRecordCounter { get; set; }
        public string TicketingAirlineCodeNumber { get; set; }
        public string CommercialAgreementReference { get; set; }
        public string CustomerFileReference { get; set; }
        public string ReportingSystemIdentifier { get; set; }
        public string SettlementAuthorisationCode { get; set; }
        public string DataInputStatusIndicator { get; set; }
        public string NetReportingMethodIndicator { get; set; }
        public string NetReportingCalculationType { get; set; }
        public string AutomatedRepricingEngineIndicator { get; set; }
        public string Reserved { get; set; }
    }
}
