//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bmd75_ECouponRecords1
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public string EMDCouponNumber { get; set; }
        public string EMDCouponValue { get; set; }
        public string EMDRelatedTicketDocumentNumber { get; set; }
        public string EMDRelatedCouponNumber { get; set; }
        public string EMDServiceType { get; set; }
        public string EMDReasonforIssuanceSubCode { get; set; }
        public string EMDFeeOwnerAirlineDesignator { get; set; }
        public string EMDExcessBaggageOverAllowanceQualifier { get; set; }
        public string EMDExcessBaggageCurrencyCode { get; set; }
        public string EMDExcessBaggageRateperUnit { get; set; }
        public string EMDExcessBaggageTotalNumberinExcess { get; set; }
        public string EMDConsumedatIssuanceIndicator { get; set; }
        public string EMDNumberofServices { get; set; }
        public string EMDOperatingCarrier { get; set; }
        public string EMDAttributeGroup { get; set; }
        public string EMDAttributeSubGroup { get; set; }
        public string EMDIndustryCarrierIndicator { get; set; }
        public string Reserved { get; set; }
        public string CurrencyType { get; set; }
    }
}
