//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMHEADER
    {
        public long Recid { get; set; }
        public string FROMAirline { get; set; }
        public string TOAirline { get; set; }
        public string CreditMemoNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string BillingMonth { get; set; }
        public string BillingPeriod { get; set; }
        public string OurRefIntUseFrom { get; set; }
        public string YourInvoiceNumber { get; set; }
        public string YourBillingMonth { get; set; }
        public string YourBillingPeriod { get; set; }
        public string OurRefIntUseTo { get; set; }
        public string SourceCode { get; set; }
        public string CorrespondanceNumber { get; set; }
        public string AttachmentIndicatorOriginal { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string CurrencyOfBillingMemo { get; set; }
        public string FIMNumber { get; set; }
        public string FIMCouponNumber { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string ReasonCode { get; set; }
        public string SettlementMethod { get; set; }
        public Nullable<int> XmlGenarated { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
