//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bmp78_SponsorInformation
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public string PrintLineIdentifier1 { get; set; }
        public string SponsorInformation1 { get; set; }
        public string PrintLineIdentifier2 { get; set; }
        public string SponsorInformation2 { get; set; }
        public string Reserved { get; set; }
    }
}
