//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boh03_ReportingAgentOfficeHeader
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string AgentNumericCode { get; set; }
        public string RemittancePeriodEndingDate { get; set; }
        public string ReservedSpace1 { get; set; }
        public string CurrencyType { get; set; }
        public string MultiLocationIdentifier { get; set; }
        public string ReservedSpace2 { get; set; }
    }
}
