//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSP_SAP_BATCH_REPORTS_KK
    {
        public string Referans { get; set; }
        public string K__A_ { get; set; }
        public string Hesap { get; set; }
        public string KDV { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string PB { get; set; }
        public string Başlık_Bilgisi { get; set; }
        public string Kalem_Açıklaması { get; set; }
        public string Masraf_Yeri_ { get; set; }
        public string Sipariş_ { get; set; }
        public string Tayin_Alanı { get; set; }
        public string Personel_No { get; set; }
        public string Kalem_Referansı_ { get; set; }
        public string Miktar { get; set; }
        public string Br { get; set; }
        public string Belge_Türü { get; set; }
        public Nullable<System.DateTime> Kayıt_Tarihi { get; set; }
        public Nullable<System.DateTime> Belge_Tarihi { get; set; }
        public string Kur { get; set; }
        public Nullable<System.DateTime> Temel_Tarih { get; set; }
        public string Kuyruk_No { get; set; }
        public string Uçak_Grubu { get; set; }
        public string Bütçe_Grubu { get; set; }
        public string Hat { get; set; }
        public string Uçuş { get; set; }
        public string Uçuş_Tarihi { get; set; }
        public string Bölge { get; set; }
        public string Motor_No { get; set; }
        public string Müşteri { get; set; }
        public int Sequence { get; set; }
        public string TransType { get; set; }
        public string Item { get; set; }
        public string BSP { get; set; }
        public string BillingMonth { get; set; }
        public int Period { get; set; }
        public string FormOfPayment { get; set; }
    }
}
