//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSP_REPORTS_KK
    {
        public string source { get; set; }
        public string RFNDTicket { get; set; }
        public string TicketNo { get; set; }
        public string IssueDate { get; set; }
        public string Route_Full { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string ADC { get; set; }
        public Nullable<decimal> COMM { get; set; }
        public Nullable<decimal> TaxOnCommission { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<decimal> Surcharges { get; set; }
        public Nullable<decimal> Tax1 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public Nullable<decimal> Tax3 { get; set; }
        public Nullable<decimal> TaxToExclude { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Cpn_Coupon { get; set; }
        public string Cpn_Route { get; set; }
        public string FareBasis { get; set; }
        public string RBD { get; set; }
        public Nullable<decimal> Cpn_ProShare { get; set; }
        public Nullable<decimal> Cpn_Tax { get; set; }
        public Nullable<decimal> Cpn_Surcharges { get; set; }
        public string Taxes { get; set; }
        public Nullable<decimal> Cpn_Total { get; set; }
        public string Cpn_FlightNo { get; set; }
        public string Cpn_FlightDate { get; set; }
        public string FormOfPayment { get; set; }
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public string AgentCode { get; set; }
        public string Period { get; set; }
        public Nullable<System.Guid> UploadGuid { get; set; }
        public string BSP { get; set; }
        public string LoadSortOrder { get; set; }
        public string TransactionNumber { get; set; }
        public string OperatingCarrier { get; set; }
        public string MarketingCarrier { get; set; }
    }
}
