//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_LiftFileList_Detail
    {
        public string ErrProc { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string UsageType { get; set; }
        public Nullable<System.Guid> UploadGuid { get; set; }
        public string ProcessingFileName { get; set; }
        public string FilePath { get; set; }
        public string Sequence { get; set; }
    }
}
