//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_LiftCouponNumber
    {
        public string ErrProc { get; set; }
        public string TktHeader { get; set; }
        public string RelatedTickets { get; set; }
        public string UsageType { get; set; }
        public string SEGNO { get; set; }
        public string TktCpn { get; set; }
        public Nullable<long> Couponnumber1 { get; set; }
        public string Sector { get; set; }
        public string TktCpn_ { get; set; }
        public string Couponnumber1_ { get; set; }
        public string Sector_ { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string FilePath { get; set; }
        public string ProcessingFileName { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public Nullable<long> RecordCount { get; set; }
        public string UserID { get; set; }
    }
}
