//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class COA4
    {
        public string ChartOfAccountCode { get; set; }
        public string Description { get; set; }
        public string PaxReferences { get; set; }
        public string TransactionCode { get; set; }
        public string DocumentType { get; set; }
        public string FormOfPayment { get; set; }
        public string Account { get; set; }
        public string CreditAccount { get; set; }
        public string DebitAccount { get; set; }
    }
}
