//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeShareAgreementDetail
    {
        public Nullable<long> RecID { get; set; }
        public string DossierNo { get; set; }
        public string CarrierName { get; set; }
        public string CarrierCode { get; set; }
        public string Type { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string ViceVersa { get; set; }
        public string InOut { get; set; }
        public string InOutLocCode { get; set; }
        public string Season { get; set; }
        public string Class { get; set; }
        public string RBD { get; set; }
        public string Routing { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string FlightNo_OWNLeg1 { get; set; }
        public string FlightNo_OALLeg1 { get; set; }
        public System.DateTime EffectiveDate_From1 { get; set; }
        public System.DateTime EffectiveDate_To1 { get; set; }
        public string FlightNo_OWNLeg2 { get; set; }
        public string FlightNo_OALLeg2 { get; set; }
        public System.DateTime EffectiveDate_From2 { get; set; }
        public System.DateTime EffectiveDate_To2 { get; set; }
        public Nullable<decimal> ISCPer { get; set; }
    }
}
