//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeShareFlights2
    {
        public int CodeShareNumber { get; set; }
        public string OperatingFlightNo { get; set; }
        public string MarketingFlightNo { get; set; }
        public string Sector { get; set; }
        public string DOW { get; set; }
        public Nullable<System.DateTime> FlightDateFrom { get; set; }
        public Nullable<System.DateTime> FlightDateTo { get; set; }
        public string DepartureLT { get; set; }
        public string ArrivalLT { get; set; }
        public string AircraftType { get; set; }
    }
}
