//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsolidatedData
    {
        public Nullable<int> SalesYear { get; set; }
        public string SalesMonthMM { get; set; }
        public string SalesMonthMMM { get; set; }
        public Nullable<int> FlightYear { get; set; }
        public string FlightMonthMM { get; set; }
        public string FlightMonthMMM { get; set; }
        public string BillingType { get; set; }
        public string RBD { get; set; }
        public string DomesticInternational { get; set; }
        public string OwnTicket { get; set; }
        public Nullable<decimal> FinalShare { get; set; }
        public Nullable<decimal> FlownRevenue { get; set; }
        public Nullable<decimal> ExpectedRevenue { get; set; }
    }
}
