//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.Invoice1 = new HashSet<Invoice1>();
        }
    
        public int ContactID { get; set; }
        public string Department { get; set; }
        public string Addressee { get; set; }
        public string Attention { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string OfficeAddress { get; set; }
        public string FOP { get; set; }
        public string CustomerNo { get; set; }
        public string BillingPeriod { get; set; }
        public string AgreementRef { get; set; }
        public string Action { get; set; }
        public string PaymentCondition { get; set; }
        public string LegalRequierements { get; set; }
        public string Remarks { get; set; }
        public string SignatureReq { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Currency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice1> Invoice1 { get; set; }
    }
}
