//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryCoordinate
    {
        public Nullable<float> latitude { get; set; }
        public Nullable<float> longitude { get; set; }
        public string alpha_2_code { get; set; }
        public string country_name { get; set; }
        public string alpha_3_code { get; set; }
        public Nullable<int> numeric_code { get; set; }
    }
}
