//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons2
    {
        public System.Guid UploadId { get; set; }
        public string RecordId { get; set; }
        public Nullable<System.Guid> HDRGUID { get; set; }
        public string Ticket { get; set; }
        public string Cpn { get; set; }
        public string StopOverTransit { get; set; }
        public string origin { get; set; }
        public string Destination { get; set; }
        public string Carrier { get; set; }
        public string FlightNo { get; set; }
        public string ClassOfService { get; set; }
        public string DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public string Status { get; set; }
        public string FareBasis { get; set; }
        public string CpnStatus { get; set; }
        public string NVB { get; set; }
        public string NVA { get; set; }
        public string FBAlawance { get; set; }
        public string RELATEDDOCUMENTNUMBER { get; set; }
        public string ConJunctionTicket { get; set; }
        public Nullable<System.Guid> RELATEDDOCUMENTGUID { get; set; }
    }
}
