//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons_Audit
    {
        public System.Guid HdrGuid { get; set; }
        public string DossierNo { get; set; }
        public string TicketNo { get; set; }
        public string RelatedNo { get; set; }
        public string CouponCode { get; set; }
        public string StopOver { get; set; }
        public string ScheduledOrigin { get; set; }
        public string ScheduledDestination { get; set; }
        public string ScheduledCarrier { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string ClassOfTravel { get; set; }
        public string FareBasis { get; set; }
        public string IntlDom { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string BillingType { get; set; }
        public string ScheduledFlight { get; set; }
        public Nullable<decimal> Proration { get; set; }
        public string Luggage { get; set; }
        public string ModifiedBy { get; set; }
        public string StationID { get; set; }
    }
}
