//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataInvoiceSummary
    {
        public long RecId { get; set; }
        public long DataTransmissionHDRID { get; set; }
        public long DataInvoicesHRDID { get; set; }
        public string TransmissionId { get; set; }
        public string InvoiceNo { get; set; }
        public string SellerOrganization_OrganizationDesignator { get; set; }
        public Nullable<int> LineItemCount { get; set; }
        public Nullable<decimal> TotalLineItemAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> TotalVATAmount { get; set; }
        public Nullable<decimal> TotalAmountWithoutVAT { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalAmountInClearanceCurrency { get; set; }
        public string AddOnChargeName { get; set; }
        public Nullable<decimal> AddOnChargeAmount { get; set; }
    }
}
