//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLineItemDetail
    {
        public long RecId { get; set; }
        public Nullable<long> DataTransmissionHDRID { get; set; }
        public Nullable<long> DataInvoicesHRDID { get; set; }
        public string TransmissionId { get; set; }
        public string InvoiceNo { get; set; }
        public string SellerOrganization_OrganizationDesignator { get; set; }
        public int DetailNumber { get; set; }
        public int LineItemNumber { get; set; }
        public Nullable<int> BatchSequenceNumber { get; set; }
        public Nullable<int> RecordSequenceWithinBatch { get; set; }
        public Nullable<decimal> ChargeAmountName___GrossBilled { get; set; }
        public string TaxType { get; set; }
        public Nullable<decimal> TaxAmountName___Billed { get; set; }
        public Nullable<decimal> TotalNetAmount { get; set; }
        public string TicketOrFIMIssuingAirline { get; set; }
        public Nullable<int> TicketOrFIMCouponNumber { get; set; }
        public string TicketDocOrFIMNumber { get; set; }
        public Nullable<int> CheckDigit { get; set; }
        public string CurrAdjustmentIndicator { get; set; }
        public string ElectronicTicketIndicator { get; set; }
        public string AirlineFlightDesignator { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FromAirportCode { get; set; }
        public string ToAirportCode { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public string ProrateMethodology { get; set; }
        public string AttachmentIndicatorOriginal { get; set; }
        public string AttachmentIndicatorValidated { get; set; }
        public Nullable<int> NumberOfAttachments { get; set; }
        public string ReferenceField10AN { get; set; }
        public string AddOnChargeName { get; set; }
        public Nullable<decimal> AddOnChargePercentage { get; set; }
        public Nullable<decimal> AddOnChargeAmount { get; set; }
        public Nullable<decimal> ChargeAmountName___GrossAccepted { get; set; }
        public Nullable<decimal> ChargeAmountName___GrossDifference { get; set; }
        public Nullable<decimal> TaxAmountName___Accepted { get; set; }
        public Nullable<decimal> TaxAmountName___Difference { get; set; }
        public string CabinClass { get; set; }
        public string BillingMemoNumber { get; set; }
        public string ReasonCode { get; set; }
        public string ReasonDescription { get; set; }
    }
}
