//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLineItemDetetailsTXBrkDnw
    {
        public long RecId { get; set; }
        public Nullable<long> DataTransmissionHDRID { get; set; }
        public Nullable<long> DataInvoicesHRDID { get; set; }
        public Nullable<long> DataLineItemDetailsID { get; set; }
        public Nullable<int> DetailNumber { get; set; }
        public Nullable<int> LineItemNumber { get; set; }
        public string TransmissionId { get; set; }
        public string InvoiceNo { get; set; }
        public string SellerOrganization_OrganizationDesignator { get; set; }
        public string TicketNo { get; set; }
        public Nullable<int> CouponNo { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxAmountName___Billed { get; set; }
        public Nullable<decimal> Billed { get; set; }
        public Nullable<decimal> Accepted { get; set; }
        public Nullable<decimal> Diff { get; set; }
    }
}
