//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTransmissionHDR
    {
        public long RecId { get; set; }
        public Nullable<System.DateTime> TransmissionDateTime { get; set; }
        public string Version { get; set; }
        public string TransmissionID { get; set; }
        public string ReceivingOrganizationID { get; set; }
        public string IssuingOrganizationID { get; set; }
        public string BillingCategory { get; set; }
        public Nullable<int> InvoiceCount { get; set; }
        public Nullable<decimal> TotalAmountCurrencyCode { get; set; }
    }
}
