//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int SPANumber { get; set; }
        public string Signatory { get; set; }
        public string FareAndPaxTypeCode { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string DiscountType { get; set; }
        public Nullable<int> Method { get; set; }
        public string InfantOccupyingSeat { get; set; }
        public string RBD { get; set; }
        public string FareBasisPrimeCode { get; set; }
        public System.DateTime IssueDateValidityFrom { get; set; }
        public Nullable<System.DateTime> IssueDateValidityTo { get; set; }
    }
}
