//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscAndBagg
    {
        public System.Guid LiftHeaderGuid { get; set; }
        public System.Guid UploadedRef { get; set; }
        public string DISCOUNT_CODE { get; set; }
        public string BAGGAGE { get; set; }
    }
}
