//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ED
    {
        public System.Guid HeaderGuid { get; set; }
        public System.Guid RelatedGuid { get; set; }
        public string DocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string Context { get; set; }
        public System.DateTime StatusDate { get; set; }
        public string Status { get; set; }
    }
}
