//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMD
    {
        public int ID { get; set; }
        public Nullable<int> Number { get; set; }
        public string SubCode { get; set; }
        public string Groups { get; set; }
        public string SubGroup { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string CommercialName { get; set; }
        public string RFIC { get; set; }
        public string RFICDescription { get; set; }
    }
}
