//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcessBaggage
    {
        public string AirlineCode { get; set; }
        public string FormAndSerialNo { get; set; }
        public string CheckDigit { get; set; }
        public Nullable<decimal> ExcessWeight { get; set; }
        public Nullable<decimal> ExcessPrice { get; set; }
        public Nullable<decimal> RatePerKG { get; set; }
        public string SkyingEquipment { get; set; }
        public string Pet { get; set; }
        public string GolfingEquipment { get; set; }
        public string BulkyBaggage { get; set; }
        public Nullable<decimal> Seats { get; set; }
        public string Others { get; set; }
        public string PlaceofIssue { get; set; }
        public string Remarks { get; set; }
        public string IssuedBy { get; set; }
    }
}
