//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        public string Category { get; set; }
        public string Validation { get; set; }
        public Nullable<int> Severity_Level { get; set; }
        public string Action { get; set; }
        public string Log { get; set; }
        public string Resolved { get; set; }
        public string EWS { get; set; }
    }
}
