//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXT83ExchangeFopBrkDwn
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string FormofPaymentAccountNumber { get; set; }
        public string CurrencyType { get; set; }
        public string DecimalPlaces { get; set; }
        public string CommissionType { get; set; }
        public string CommissionRate { get; set; }
        public string CommissionAmount { get; set; }
        public string TaxMiscellaneousFeeType1 { get; set; }
        public string TaxMiscellaneousFeeTypeSubCode1 { get; set; }
        public string TaxMiscellaneousFeeAmount1 { get; set; }
        public string TaxMiscellaneousFeeType2 { get; set; }
        public string TaxMiscellaneousFeeTypeSubCode2 { get; set; }
        public string TaxMiscellaneousFeeAmount2 { get; set; }
        public string TaxMiscellaneousFeeType3 { get; set; }
        public string TaxMiscellaneousFeeTypeSubCode3 { get; set; }
        public string TaxMiscellaneousFeeAmount3 { get; set; }
        public string SourceofTotalAmount { get; set; }
        public string SourceofTaxBreakdown { get; set; }
        public string Filler { get; set; }
    }
}
