//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareBasis3
    {
        public System.Guid HdrGuid { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public int CouponNumber { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string MappedPrimeCode { get; set; }
        public string FareCategory { get; set; }
        public string PrimeCode { get; set; }
        public string SeasonalCode { get; set; }
        public string PartOfWeekCode { get; set; }
        public string PartOfDayCode { get; set; }
        public string FareAndPaxTypeCode { get; set; }
        public string MaximumValidity { get; set; }
        public string FareLevelIdentifier { get; set; }
        public string FareAndPassengerTypeCodeDiscount { get; set; }
        public string Discount { get; set; }
        public string ClassificationDesignator { get; set; }
        public string ReservationEntitlement { get; set; }
    }
}
