//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareComponent
    {
        public System.Guid RelatedDocumentGuid { get; set; }
        public Nullable<int> FareComponent1 { get; set; }
        public Nullable<decimal> NUC { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string HIP { get; set; }
        public string OriginDestination { get; set; }
        public string FareBasis { get; set; }
        public int CouponNumber { get; set; }
        public string Begin { get; set; }
        public string Carrier { get; set; }
        public string End { get; set; }
        public Nullable<decimal> Q { get; set; }
        public Nullable<decimal> S { get; set; }
        public string ITBT { get; set; }
    }
}
