//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareBasisRule
    {
        public string ContractNo { get; set; }
        public string SPAID { get; set; }
        public long RECID { get; set; }
        public string Parameter { get; set; }
        public string FareBasis { get; set; }
        public string Evaluate { get; set; }
        public string Value { get; set; }
        public string Result { get; set; }
    }
}
