//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareType
    {
        public string ContractNo { get; set; }
        public string SPAID { get; set; }
        public string ITBT { get; set; }
        public string OW { get; set; }
        public string RT { get; set; }
        public string OJ { get; set; }
        public string CT { get; set; }
        public string FareBasis_IN { get; set; }
        public string FareBasis_EX { get; set; }
    }
}
