//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareControl
    {
        public string OrigCity { get; set; }
        public string DestCity { get; set; }
        public string PrimeCode { get; set; }
        public string RBD { get; set; }
        public Nullable<decimal> MinSectorVal { get; set; }
        public Nullable<decimal> MaxSectorVal { get; set; }
        public Nullable<int> Validated { get; set; }
    }
}
