//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCA_Component
    {
        public System.Guid HdrGuid { get; set; }
        public string FareComponents { get; set; }
        public Nullable<decimal> NUC { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ROE { get; set; }
        public Nullable<decimal> SpecidiedStopOver { get; set; }
        public Nullable<decimal> UnSpecifiedStopOver { get; set; }
        public Nullable<decimal> TotalStopOver { get; set; }
        public Nullable<decimal> Q { get; set; }
        public Nullable<decimal> D { get; set; }
        public Nullable<decimal> P { get; set; }
        public string Journey { get; set; }
    }
}
