//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIM_OB
    {
        public string FIMNumber { get; set; }
        public string TicketOrFIMIssuingAirline { get; set; }
        public string TicketDocOrFIMNumber { get; set; }
        public int TicketOrFIMCouponNumber { get; set; }
        public string PMC { get; set; }
        public string AirlineFlightDesignator { get; set; }
        public string CheckDigit { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FromAirportCode { get; set; }
        public string ToAirportCode { get; set; }
        public Nullable<decimal> FinalShare { get; set; }
        public string CurrAdjustmentIndicator { get; set; }
        public string InvoiceNo { get; set; }
        public string BillingPeriod { get; set; }
    }
}
