//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIMDetailsEntry
    {
        public long Recid { get; set; }
        public long FIMHeaderRecId { get; set; }
        public string FIMNumber { get; set; }
        public int RecordNumber { get; set; }
        public string PassengerName { get; set; }
        public string CouponNumber { get; set; }
        public string AirlineCode { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public string DocumentType { get; set; }
        public string FareBasis_PaxTypeCode { get; set; }
        public string NewFlightNo1 { get; set; }
        public Nullable<decimal> Billed1 { get; set; }
        public Nullable<decimal> Accepted1 { get; set; }
        public Nullable<decimal> Difference1 { get; set; }
        public Nullable<int> ExcessBaggageWeight1 { get; set; }
        public Nullable<int> ExcessBaggagePeice1 { get; set; }
        public Nullable<int> Indicator1 { get; set; }
        public string NewFlightNo2 { get; set; }
        public Nullable<decimal> Billed2 { get; set; }
        public Nullable<decimal> Accepted2 { get; set; }
        public Nullable<decimal> Difference2 { get; set; }
        public Nullable<int> ExcessBaggageWeight2 { get; set; }
        public Nullable<int> ExcessBaggagePeice2 { get; set; }
        public Nullable<int> Indicator2 { get; set; }
    }
}
