//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIMHeaderData
    {
        public long Recid { get; set; }
        public string FIMNumber { get; set; }
        public string OWN_AOL { get; set; }
        public string OriginalFlightNumber { get; set; }
        public Nullable<System.DateTime> OriginalFlightDate { get; set; }
        public string SectorFrom { get; set; }
        public string AirlineId { get; set; }
        public string RoutedFromFlightNo { get; set; }
        public Nullable<System.DateTime> RoutedFromDate { get; set; }
        public string PlaceOfInterruption { get; set; }
        public string RoutedTo1 { get; set; }
        public string RoutedTo_Airline1 { get; set; }
        public string RoutedTo_FlightNumber1 { get; set; }
        public Nullable<System.DateTime> RoutedTo_Date1 { get; set; }
        public string RoutedTo_From1 { get; set; }
        public string RoutedTo_To1 { get; set; }
        public string RoutedTo2 { get; set; }
        public string RoutedTo_Airline2 { get; set; }
        public string RoutedTo_FlightNumber2 { get; set; }
        public System.DateTime RoutedTo_Date2 { get; set; }
        public string RoutedTo_From2 { get; set; }
        public string RoutedTo_To2 { get; set; }
        public string ReasonForIssurance { get; set; }
        public string DiversionByCarrierCode { get; set; }
        public string TotalNoOfPassencer { get; set; }
        public string ValidatorName { get; set; }
        public Nullable<int> FIMDocReceived { get; set; }
        public string TempFIMNumber { get; set; }
        public string Status { get; set; }
        public string OriginalSector { get; set; }
        public Nullable<int> XmlGenetared { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string Remark { get; set; }
        public string BillingPeriod { get; set; }
    }
}
