//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIMHeader
    {
        public System.Guid RelatedGuid { get; set; }
        public string FIMNO { get; set; }
        public string OriginalFlightNo { get; set; }
        public Nullable<System.DateTime> OriginalFlightDate { get; set; }
        public string Sector { get; set; }
        public string RoutedFrom { get; set; }
        public string PlaceOfInterruption { get; set; }
        public string RoutedTo1 { get; set; }
        public string Airline1 { get; set; }
        public string FlightNo1 { get; set; }
        public string Date1 { get; set; }
        public string From1 { get; set; }
        public string To1 { get; set; }
        public string RoutedTo2 { get; set; }
        public string Airline2 { get; set; }
        public string FlightNo2 { get; set; }
        public string Date2 { get; set; }
        public string From2 { get; set; }
        public string To2 { get; set; }
        public string ReasonForIssurane { get; set; }
        public string DiversionByCarrierCode { get; set; }
        public string TotalNoOfPassengers { get; set; }
        public string Validator { get; set; }
    }
}
