//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightsSchedule
    {
        public long RecId { get; set; }
        public string DataFileName { get; set; }
        public string TypeOfFlight { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FlightNumber { get; set; }
        public string Segment { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Equipment { get; set; }
        public string Plate { get; set; }
        public string Category { get; set; }
        public string KMS { get; set; }
        public string SegmentStatus { get; set; }
        public Nullable<int> TotalOWNCoupon { get; set; }
        public Nullable<int> TotalInterlineCoupon { get; set; }
        public Nullable<int> TotalMCOCoupon { get; set; }
        public Nullable<int> TotalExcessBaggageCoupon { get; set; }
        public Nullable<int> TotalAdult { get; set; }
        public Nullable<int> TotalChilds { get; set; }
        public Nullable<int> TotalInfants { get; set; }
        public string Observation { get; set; }
    }
}
