//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightsScheduleDone
    {
        public long RecId { get; set; }
        public string DataFileName { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string AcReg { get; set; }
        public string Carr { get; set; }
        public string Flt1 { get; set; }
        public string Origin { get; set; }
        public string L1Off { get; set; }
        public Nullable<int> INF { get; set; }
        public Nullable<int> TOT { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<int> REV { get; set; }
        public string To1 { get; set; }
        public string Tag { get; set; }
    }
}
