//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSchedule_RAW_SD
    {
        public System.DateTime DATE { get; set; }
        public string AC { get; set; }
        public string FLTNO { get; set; }
        public string REG { get; set; }
        public string ROUTE { get; set; }
        public string BHRS { get; set; }
        public string BOFF { get; set; }
        public string REMARKS { get; set; }
        public string SERNO { get; set; }
    }
}
