//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRestriction1
    {
        public string ContractNo { get; set; }
        public string SPAID { get; set; }
        public long RECID { get; set; }
        public Nullable<int> FlightFrom { get; set; }
        public Nullable<int> FlightTo { get; set; }
    }
}
