//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRestriction
    {
        public int SPANumber { get; set; }
        public string Carrier { get; set; }
        public int FlightFrom { get; set; }
        public int FlightTo { get; set; }
        public System.DateTime ValidityFrom { get; set; }
        public Nullable<System.DateTime> ValidityTo { get; set; }
    }
}
