//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRecord1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightRecord1()
        {
            this.SLS = new HashSet<SL>();
        }
    
        public string FlightKey { get; set; }
        public System.DateTime FlightDate { get; set; }
        public int FlightNumber { get; set; }
        public string FlightNumberSuffix { get; set; }
        public string AirlineCode { get; set; }
        public string AircraftRegistrationNumber { get; set; }
        public string StationOfLoading { get; set; }
        public string AircraftVersion { get; set; }
        public Nullable<System.DateTime> LocalDate { get; set; }
        public string SupplementaryInfo { get; set; }
        public string STC { get; set; }
        public string ProductCode { get; set; }
        public Nullable<bool> IgnoreFlag { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SL> SLS { get; set; }
    }
}
