//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSchedule_MD
    {
        public System.DateTime DateVol { get; set; }
        public string NumVol { get; set; }
        public string Appareil { get; set; }
        public string ScheduledDep { get; set; }
        public string ScheduledArr { get; set; }
        public Nullable<System.TimeSpan> STD { get; set; }
        public Nullable<System.TimeSpan> STA { get; set; }
        public Nullable<System.TimeSpan> ATD { get; set; }
        public Nullable<System.TimeSpan> ATA { get; set; }
        public Nullable<int> PREV_JJ { get; set; }
        public Nullable<int> PREV_SS { get; set; }
        public Nullable<int> PREV_YY { get; set; }
        public Nullable<int> PREV_BB { get; set; }
        public Nullable<int> JJ { get; set; }
        public Nullable<int> SS { get; set; }
        public Nullable<int> YY { get; set; }
        public Nullable<int> BB { get; set; }
        public string Code_Retard { get; set; }
        public string Retard { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
    }
}
