//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSchedule
    {
        public System.DateTime FlightDate { get; set; }
        public string Sector { get; set; }
        public Nullable<int> FlightCount { get; set; }
        public string FlightType { get; set; }
    }
}
