//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSchedule_MD1
    {
        public string SAISON { get; set; }
        public int MOIS { get; set; }
        public string CIE { get; set; }
        public int NUM_VOL { get; set; }
        public string RESEAU { get; set; }
        public string DEP_ARR { get; set; }
        public string DAYOPS { get; set; }
        public string ACFT { get; set; }
        public int DISTANCE { get; set; }
        public System.TimeSpan DEP_UTC { get; set; }
        public System.TimeSpan ARR_UTC { get; set; }
        public string IMMA { get; set; }
        public decimal HDV { get; set; }
        public int SO { get; set; }
        public System.DateTime DATE_VOL { get; set; }
    }
}
