//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlownNoMatching
    {
        public string TicketDocumentNumber { get; set; }
        public string UsageAirline { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string AirlineCode { get; set; }
        public string CheckDigit { get; set; }
        public string CouponNumber { get; set; }
        public string Couponnumber1 { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string AirlineCode1 { get; set; }
        public string FlightNumber { get; set; }
        public string Sector { get; set; }
        public Nullable<System.DateTime> LocalFlightDate { get; set; }
        public string SellingClass { get; set; }
        public string FareBasis { get; set; }
        public string Reservationstatus { get; set; }
        public string FreeBaggageAllowance { get; set; }
        public string Involuntaryindicator { get; set; }
        public string Stopovercode { get; set; }
        public Nullable<System.DateTime> NotValidbeforedate { get; set; }
        public Nullable<System.DateTime> NotValidafterDate { get; set; }
        public System.Guid LiftHeaderGuid { get; set; }
    }
}
