//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlownHeader
    {
        public System.Guid LiftHeaderGuid { get; set; }
        public string AirlineCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public string CouponNumber { get; set; }
        public Nullable<System.DateTime> Localdeparturedate { get; set; }
        public string FlightNumber { get; set; }
        public string UsedClassofService { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string UsageType { get; set; }
        public string UsageAirline { get; set; }
        public string UsageFlightNumber { get; set; }
        public Nullable<System.DateTime> LocalFlightDate { get; set; }
        public Nullable<System.DateTime> SoldLocalDepartureDate { get; set; }
        public string SaleOriginCode { get; set; }
        public string SaleDestinationCode { get; set; }
        public string UsageOriginCode { get; set; }
        public string UsageDestinationCode { get; set; }
        public string Sector { get; set; }
        public Nullable<decimal> ReportedFare { get; set; }
        public string Currencyofreportedfare { get; set; }
        public string EquivalentFareinPaymentCurrency { get; set; }
        public string PaymentCurrency { get; set; }
        public string AgencyNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string BookingReference { get; set; }
        public string TourCode { get; set; }
        public string PassengerName { get; set; }
        public string SettlementAuthorizationcode { get; set; }
        public string TicketnumberFirstinSet { get; set; }
        public string TicketnumberSecondinSet { get; set; }
        public string TicketnumberThirdinSet { get; set; }
        public string TicketnumberFourthinSet { get; set; }
        public string FareConstruction { get; set; }
        public string TicketDocumentAmountasonticket { get; set; }
        public string TicketDocumentAmountCurrency { get; set; }
        public string TicketingModeIndicator { get; set; }
        public string NetRemitIndicator { get; set; }
        public string CommissionRate { get; set; }
        public string CommissionAmount { get; set; }
        public string CurrencyofCommissionAmount { get; set; }
        public string Originalticketdocumentnumber1 { get; set; }
        public string Originalticketdocumentnumber2 { get; set; }
        public string Originalticketdocumentnumber3 { get; set; }
        public string Originalticketdocumentnumber4 { get; set; }
        public string Originalticketdocumentnumber5 { get; set; }
        public string Originalticketdocumentnumber6 { get; set; }
        public string Originalticketdocumentnumber7 { get; set; }
        public string OriginalIssueInformation { get; set; }
        public string InternationalSaleIndicator { get; set; }
        public string EndorsementRestrictionText { get; set; }
        public string AmountEnteredbyAgent { get; set; }
        public string CurrencyofAmountEnteredbyAgent { get; set; }
        public string TransactionTotalAmount { get; set; }
        public string CurrencyofTransactionTotalAmount { get; set; }
        public string Additionalcollectiontotal { get; set; }
        public string CurrencyofAdditionalCollection { get; set; }
        public string FareCalculationModeIndicator { get; set; }
        public Nullable<decimal> Bankersexchangerate { get; set; }
        public string Documenttype { get; set; }
        public string Nonendorsableindicator { get; set; }
        public string Nonrefundableindicator { get; set; }
        public string Penaltyrestrictionindicator { get; set; }
        public string ReIssueDocumentNumber { get; set; }
        public string ReIssueLocation { get; set; }
        public string ReIssueDate { get; set; }
        public string ReIssueAgency { get; set; }
        public string FareException { get; set; }
        public System.Guid UploadGuid { get; set; }
    }
}
