//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOP1
    {
        public System.Guid LiftHeaderGuid { get; set; }
        public string RecordType { get; set; }
        public string AirlineCode { get; set; }
        public string EMDNumber { get; set; }
        public string CheckDigit { get; set; }
        public string CouponNumber { get; set; }
        public Nullable<int> Seqno { get; set; }
        public string FOP1Type1 { get; set; }
        public string FOP1Decamount1 { get; set; }
        public string FOP1Curramount1 { get; set; }
        public string FOP1amount1 { get; set; }
        public string FOP1Creditcardtype1 { get; set; }
        public string FOP1CreditcardNumber1 { get; set; }
        public string FOP1CreditcardExpirydate1 { get; set; }
        public string FOP1CreditcardApprovalCode1 { get; set; }
        public string OLDFOP1Type1 { get; set; }
        public string OLDFOP1Decamount1 { get; set; }
        public string OLDFOP1Curramount1 { get; set; }
        public string OLDFOP1amount1 { get; set; }
        public string OLDFOP1Creditcardtype1 { get; set; }
        public string OLDFOP1CreditcardNumber1 { get; set; }
        public string OLDFOP1CreditcardExpirydate1 { get; set; }
        public string OLDFOP1CreditcardApprovalCode1 { get; set; }
    }
}
