//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormOfPayment
    {
        public System.Guid FOPGuid { get; set; }
        public string PaymentMode { get; set; }
        public string CardCode { get; set; }
        public string FOPDelimiter { get; set; }
        public int FormOfPayment_ID { get; set; }
        public string FormOfPayment1 { get; set; }
        public string Description { get; set; }
    }
}
