//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORWARDSALE
    {
        public long FORWARDSALESID { get; set; }
        public string TICKETNUMBER { get; set; }
        public string RelatedDocumentNo { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> RateofExchange { get; set; }
        public Nullable<decimal> SALES { get; set; }
        public Nullable<decimal> CPN { get; set; }
        public Nullable<decimal> FORWARDSALESTFCs { get; set; }
        public Nullable<decimal> BE { get; set; }
        public Nullable<decimal> TR { get; set; }
        public Nullable<decimal> DE { get; set; }
        public Nullable<decimal> TFCEXCHANGE { get; set; }
        public Nullable<decimal> TFCREFUND { get; set; }
        public Nullable<decimal> FORWARDSALES1 { get; set; }
        public Nullable<decimal> SURCHARGES { get; set; }
        public Nullable<decimal> FORWARDSALES2 { get; set; }
        public decimal CPNNO { get; set; }
        public Nullable<decimal> TRANSACTIONMONTH { get; set; }
        public Nullable<decimal> PROVISION_CPNVALUE_MOS { get; set; }
        public Nullable<decimal> UPDATEDPROVISION_MOC { get; set; }
        public Nullable<decimal> NETFLOWNREVENUE { get; set; }
        public Nullable<decimal> INTERLINEACCOUNTSPAYABLENET { get; set; }
        public Nullable<decimal> REJECTION1 { get; set; }
        public Nullable<decimal> REJECTION2 { get; set; }
        public Nullable<decimal> REJECTION3 { get; set; }
        public Nullable<decimal> EXCHANGE { get; set; }
        public Nullable<decimal> FAREREFUND { get; set; }
        public Nullable<decimal> UNEARNEDREVENUE { get; set; }
        public Nullable<decimal> ISC { get; set; }
        public Nullable<decimal> SALESCOMMPAID { get; set; }
        public Nullable<decimal> CCARDCOMMPAID { get; set; }
        public Nullable<decimal> UATPISSSUERDISCOUNT { get; set; }
        public Nullable<decimal> ISCADJ { get; set; }
        public Nullable<decimal> CRPD1 { get; set; }
        public Nullable<decimal> REJECTION_TFC1 { get; set; }
        public Nullable<decimal> REJECTION_TFC2 { get; set; }
        public Nullable<decimal> REJECTION_TFC3 { get; set; }
        public Nullable<decimal> EOMADJ { get; set; }
        public Nullable<decimal> DIFFERENCEINEXCHANGE { get; set; }
        public string TOTALTRANSACTIONS { get; set; }
    }
}
