//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class frUserChanx
    {
        public System.Guid FRGuid { get; set; }
        public string PrimeGuid { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
        public Nullable<decimal> ISCPercentage { get; set; }
        public Nullable<decimal> ISCAmount { get; set; }
        public Nullable<decimal> OriginalEvaluation { get; set; }
        public Nullable<decimal> RevisedEvaluation { get; set; }
        public Nullable<decimal> OALNet { get; set; }
        public Nullable<decimal> OWNNet { get; set; }
        public Nullable<decimal> WeAcceptAmt { get; set; }
        public Nullable<decimal> WeRejectAmt { get; set; }
        public string RejectionReason { get; set; }
        public string AdditionalRemarks { get; set; }
        public Nullable<decimal> TFCBilled { get; set; }
        public Nullable<decimal> TFCAccept { get; set; }
        public Nullable<decimal> TFCDifference { get; set; }
        public Nullable<System.Guid> ProrateDetailGuid { get; set; }
        public Nullable<System.Guid> ProrateStepGuid { get; set; }
        public string Attachments { get; set; }
        public string Method { get; set; }
        public string ITBT { get; set; }
        public string RBD { get; set; }
        public string FareBasis { get; set; }
        public string EndorsementBox { get; set; }
        public string SPAApplicability { get; set; }
        public string SettlementMonthPeriod { get; set; }
        public string FromAirportCode { get; set; }
        public string ToAirportCode { get; set; }
        public string Mode { get; set; }
    }
}
