//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSP
    {
        public string Parameter { get; set; }
        public string String1 { get; set; }
        public string String2 { get; set; }
        public string String3 { get; set; }
        public string String4 { get; set; }
        public Nullable<decimal> Numeric1 { get; set; }
        public Nullable<decimal> Numeric2 { get; set; }
        public Nullable<long> Integer1 { get; set; }
        public Nullable<long> Integer2 { get; set; }
        public Nullable<long> Integer3 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string ParameterType { get; set; }
        public Nullable<int> PrivacyLevel { get; set; }
        public string Description { get; set; }
    }
}
