//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class HdrGuidFromLiftHeader
    {
        public System.Guid HdrGuid { get; set; }
        public System.Guid LiftHeaderGuid { get; set; }
        public System.Guid UploadGuid { get; set; }
        public Nullable<System.DateTime> BatchID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
