//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public System.Guid LiftHeaderGuid { get; set; }
        public string RecordType { get; set; }
        public string AirlineCode { get; set; }
        public string EMDNumber { get; set; }
        public string CheckDigit { get; set; }
        public string CouponNumber { get; set; }
        public string UsageType { get; set; }
        public string ManualIndicator { get; set; }
        public string UsagePerformer { get; set; }
        public string UsageMarketingcarrier { get; set; }
        public string UsageOperatingcarrier { get; set; }
        public string UsageOriginCode { get; set; }
        public string UsageDestinationCode { get; set; }
        public string SettlementAuthorizationcode { get; set; }
        public string InConnectionWithTicketNumber { get; set; }
        public string InConnectionWithCouponNumber { get; set; }
        public string Associationstatus { get; set; }
        public string SoldMarketingcarrier { get; set; }
        public string SoldOperatingcarrier { get; set; }
        public string Reasonforissuancesubcode { get; set; }
        public string SoldOriginCode { get; set; }
        public string SoldDestinationCode { get; set; }
        public string Excessbaggagetotalnumberofunits { get; set; }
        public string Excessbaggagechargequalifier { get; set; }
        public string Excessbaggageunitqualifier { get; set; }
        public string Excessbaggagechargecurrency { get; set; }
        public string Excessbaggagerateperunit { get; set; }
        public string CouponValue { get; set; }
        public string ReportedFare { get; set; }
        public string Currencyofreportedfare { get; set; }
        public string EquivalentFareinPaymentCurrency { get; set; }
        public string PaymentCurrency { get; set; }
        public string AgencyNumber { get; set; }
        public string IssueDate { get; set; }
        public string IssuingOfficelocation { get; set; }
        public string BookingReference { get; set; }
        public string TourCode { get; set; }
        public string PassengerName { get; set; }
        public string Reasonforissuancecode { get; set; }
        public string EMDnumberFirstinSet { get; set; }
        public string EMDnumberSecondinSet { get; set; }
        public string EMDnumberThirdinSet { get; set; }
        public string EMDnumberFourthinSet { get; set; }
        public string EMDDocumentAmountasonEMD { get; set; }
        public string EMDDocumentAmountCurrency { get; set; }
        public string NonExchangeableAmount { get; set; }
        public string CurrencyofNonExchangeableAmount { get; set; }
        public string NonRefundableAmount { get; set; }
        public string CurrencyofNonRefundableAmount { get; set; }
        public string TransactionTotalAmount { get; set; }
        public string CurrencyofTransactionTotalAmount { get; set; }
        public string Additionalcollectiontotal { get; set; }
        public string CurrencyofAdditionalCollection { get; set; }
        public string FareConstruction { get; set; }
        public string FareCalculationModeIndicator { get; set; }
        public string CommissionRate { get; set; }
        public string CommissionAmount { get; set; }
        public string CurrencyofCommissionAmount { get; set; }
        public string Bankersexchangerate { get; set; }
        public string NetFare { get; set; }
        public string CurrencyofNetFare { get; set; }
        public string FormofIdentificationtype { get; set; }
        public string FormofIdentificationnumber { get; set; }
        public string FormofIdentificationairlineVendorcodePartyName { get; set; }
        public string FrequentFlyerairlinecode { get; set; }
        public string FrequentFlyerCustomercode { get; set; }
        public string OriginalIssueInformation { get; set; }
        public string ExchangedEMDdocumentnumber1 { get; set; }
        public string ExchangedEMDdocumentnumber2 { get; set; }
        public string ExchangedEMDdocumentnumber3 { get; set; }
        public string ExchangedEMDdocumentnumber4 { get; set; }
        public string ExchangedEMDdocumentnumber5 { get; set; }
        public string ExchangedEMDdocumentnumber6 { get; set; }
        public string ExchangedEMDdocumentnumber7 { get; set; }
        public string InternationaldomesticIndicator { get; set; }
        public string EndorsementRestrictionText { get; set; }
        public string TicketingModeIndicator { get; set; }
        public string NetReportingIndicator { get; set; }
        public string Nonendorsableindicator { get; set; }
        public string PresentCreditCardindicator { get; set; }
        public Nullable<System.Guid> UploadGuid { get; set; }
    }
}
