//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class IataReferenceFile
    {
        public string Serial_No_ { get; set; }
        public string Participant_Code { get; set; }
        public string Location_Id { get; set; }
        public string Active { get; set; }
        public string Member_Legal_Name { get; set; }
        public string Tax_Vat_Registration_Id { get; set; }
        public string Additional_Tax_Vat_Registration_Id { get; set; }
        public string Company_Registration_Id { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Address_Line_3 { get; set; }
        public string City_Name { get; set; }
        public string Subdivision_Code { get; set; }
        public string Subdivision_Name { get; set; }
        public string Country_Code { get; set; }
        public string Country_Name { get; set; }
        public string Postal_Code { get; set; }
    }
}
