//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportData
    {
        public System.Guid hdrGuid { get; set; }
        public System.Guid UploadedRef { get; set; }
        public string FileHeaderSignature { get; set; }
        public string CREATION_DATE { get; set; }
        public string CREATION_TIME { get; set; }
        public string RECORD_TYPE { get; set; }
        public string ACTUAL_AIRLINE_ALPHA_CODE { get; set; }
        public string ACTUAL_FLIGHT_NUM_CODE { get; set; }
        public string ACTUAL_FLIGHT_DATE_UTC { get; set; }
        public string ACTUAL_ORIGIN { get; set; }
        public string ACTUAL_DESTINATION_ { get; set; }
        public string DOCUMENT_AIRLINE_NUM { get; set; }
        public string DOCUMENT_FORM_CODE_SERIAL_NUM { get; set; }
        public string DOCUMENT_CHECK_DIGIT { get; set; }
        public string COUPON_NUMBER { get; set; }
        public string SALES_LOCATION_CODE { get; set; }
        public string FARE_BASE_TICKET_DESIGNATOR { get; set; }
        public string PLANNED_CARRIER { get; set; }
        public string PLANNED_FLIGHT_NUMBER { get; set; }
        public string PLANNED_FLIGHT_DATE { get; set; }
        public string FREQUENT_FLYER_AIRLINE_CODE { get; set; }
        public string CUST_NUM { get; set; }
        public string DOCUMENT_ISSUE_DATE { get; set; }
        public string DECIMAL_FARE_AMOUNT { get; set; }
        public string CURRENCY_CODE_FARE_AMOUNT { get; set; }
        public string FARE_AMOUNT { get; set; }
        public string DECIMAL_EQUIVALENT_AMOUNT { get; set; }
        public string CURRENCY_CODE_EQUIVALENT_AMT { get; set; }
        public string EQUIVALENT_AMOUNT { get; set; }
        public string TOTAL_AMOUNT { get; set; }
        public string CURRENCY_CODE_TOTAL_AMOUNT { get; set; }
        public string TOTAL_AMOUNT1 { get; set; }
        public string AMOUNT_TYPE { get; set; }
        public string DECIMAL_AMOUNT_TAX { get; set; }
        public string CURRENCY_AMOUNT_TAX1 { get; set; }
        public string AMOUNT_TAX1 { get; set; }
        public string AMOUNT_TAX_CODE1 { get; set; }
        public string DECIMAL_AMOUNT_TAX2 { get; set; }
        public string CURRENCY_AMOUNT_TAX2 { get; set; }
        public string AMOUNT_TAX2 { get; set; }
        public string AMOUNT_TAX_CODE2 { get; set; }
        public string DECIMAL_AMOUNT_TAX3 { get; set; }
        public string CURRENCY_AMOUNT_TAX3 { get; set; }
        public string AMOUNT_TAX3 { get; set; }
        public string AMOUNT_TAX_CODE3 { get; set; }
        public string FOP_1_TYPE { get; set; }
        public string DECIMAL_FOP_1_AMOUNT { get; set; }
        public string CURRENCY_FOP_1_AMOUNT { get; set; }
        public string FOP_1_AMOUNT { get; set; }
        public string FOP_2_TYPE { get; set; }
        public string DECIMAL_FOP_2_AMOUNT { get; set; }
        public string CURRENCY_FOP_2_AMOUNT { get; set; }
        public string FOP_2_AMOUNT { get; set; }
        public string NAME { get; set; }
        public string DISCOUNT_CODE { get; set; }
        public string FLIGHT_PLANNED_FROM { get; set; }
        public string FLIGHT_PLANNED_TO { get; set; }
        public string CLASS_OF_BOOKING { get; set; }
        public string BAGGAGE { get; set; }
        public string FLOWN_FLIGHT_CLASS { get; set; }
        public string Electronic_Sales_Authorization_Code { get; set; }
        public string MCO_TYPE { get; set; }
        public string FARE_CALC_1 { get; set; }
        public string FARE_CALC_2 { get; set; }
        public string FARE_CALC_3 { get; set; }
        public string FARE_CALC_4 { get; set; }
        public string filler { get; set; }
    }
}
