//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class INADProrateDetail
    {
        public string DocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string SectorOrigin { get; set; }
        public string SectorDestination { get; set; }
        public string Carrier { get; set; }
        public string ProrateFactor { get; set; }
        public Nullable<decimal> ProrateShareUncollectedFareGross { get; set; }
        public Nullable<decimal> ProrateShareUncollectedFareISC { get; set; }
        public Nullable<decimal> ProrateShareUncollectedFareNet { get; set; }
        public Nullable<decimal> ProrateShareUncollectedNTC { get; set; }
    }
}
