//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string FOP { get; set; }
        public string DocumentNumber { get; set; }
    
        public virtual Invoice1 Invoice1 { get; set; }
    }
}
