//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAnalyticsTaxBkDwn
    {
        public long RecId { get; set; }
        public string InvoiceNumber { get; set; }
        public string SellerOrganization_OrganizationDesignator { get; set; }
        public string Carrier { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string ChargeCode { get; set; }
        public string NewChargeCode { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> Billed { get; set; }
        public Nullable<decimal> Accepted { get; set; }
        public Nullable<decimal> Diff { get; set; }
    }
}
