//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAnalyticsAOCharge
    {
        public Nullable<long> recId { get; set; }
        public string TransmissionId { get; set; }
        public string InvoiceNumber { get; set; }
        public string SellerOrganization_OrganizationDesignator { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> LineItemNumber { get; set; }
        public Nullable<int> DetailNumber { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string YourAddOnDescription { get; set; }
        public Nullable<decimal> YourAddOnPerecentage { get; set; }
        public Nullable<decimal> YourAddOnAmount { get; set; }
        public decimal OurAddOnPercentage { get; set; }
        public Nullable<decimal> OurAddOnAmount { get; set; }
        public Nullable<decimal> Accepted { get; set; }
        public Nullable<decimal> Difference { get; set; }
    }
}
