//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inward_Header
    {
        public string Reference { get; set; }
        public string InvoiceNo { get; set; }
        public string BillingPeriod { get; set; }
        public int SourceCode { get; set; }
        public long BatchNo { get; set; }
        public string BillingAirline { get; set; }
        public string BilledAirline { get; set; }
        public string sourceDoc { get; set; }
    }
}
