//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardImport
    {
        public Nullable<int> SerialNo { get; set; }
        public string BillingAirlineCode { get; set; }
        public string BilledAirlineCode { get; set; }
        public string InvoiceNumber { get; set; }
        public string BillingMonth_Year { get; set; }
        public Nullable<int> PeriodNo { get; set; }
        public string Sample_NonSample { get; set; }
        public string SourceCode { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string IssuingAirline { get; set; }
        public int CpnNo { get; set; }
        public string TicketNumber { get; set; }
        public string CheckDigit { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public string CurrencyofListing { get; set; }
        public Nullable<decimal> GrossFareValue { get; set; }
        public string ETicketIndicator { get; set; }
        public string OrigPMI { get; set; }
        public string AgmtIndcSupp { get; set; }
        public Nullable<double> ISCRate { get; set; }
        public Nullable<double> ISCAmount { get; set; }
        public Nullable<double> OtherCommRate { get; set; }
        public Nullable<double> OtherCommAmount { get; set; }
        public Nullable<double> UATPRate { get; set; }
        public Nullable<double> UATPAmount { get; set; }
        public Nullable<double> HandlingFeeAmount { get; set; }
        public string CurrAdjInd { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> CouponTotalAmount { get; set; }
        public string BillingCarrier { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateImported { get; set; }
    }
}
