//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardRejectionTaxMemo
    {
        public string InvoiceNumber { get; set; }
        public int SerialNo { get; set; }
        public string TFC { get; set; }
        public Nullable<double> TFC_Your_Billing { get; set; }
        public Nullable<double> TFC_We_Accept { get; set; }
        public Nullable<double> TFC_Difference { get; set; }
        public System.Guid PrimeGuid { get; set; }
    }
}
