//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It01_FileHeader
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string SystemProviderReportingPeriodEndingDate { get; set; }
        public string ReportingSystemIdentifier { get; set; }
        public string HandbookRevisionNumber { get; set; }
        public string TestProductionStatus { get; set; }
        public string ProcessingDate { get; set; }
        public string ProcessingTime { get; set; }
        public string ISOCountryCode { get; set; }
        public string ReservedSpace { get; set; }
        public string FileType { get; set; }
        public string FileTypeSequenceNumber { get; set; }
        public string ReservedSpace1 { get; set; }
    }
}
