//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It02_Transaction
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string TransactionNumber { get; set; }
        public string AgentNumericCode { get; set; }
        public string ConjunctionTicketIndicator { get; set; }
        public string CouponUseIndicator { get; set; }
        public string DateofIssue { get; set; }
        public string StatisticalCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public string TransactionCode { get; set; }
        public string TransmissionControlNumber { get; set; }
        public string TransmissionControlNumberCheckDigit { get; set; }
        public string TicketingAirlineCodeNumber { get; set; }
        public string CheckDigit1 { get; set; }
        public string FormatIdentifier { get; set; }
        public string PassengerName { get; set; }
        public string ApprovedLocationType { get; set; }
        public string StockControlNumberFrom { get; set; }
        public string StockControlNumberTo { get; set; }
        public string ApprovedLocationNumericCode { get; set; }
        public string ApprovedLocationType1 { get; set; }
        public string StockControlNumberFrom1 { get; set; }
        public string StockControlNumberTo1 { get; set; }
        public string ApprovedLocationNumericCode1 { get; set; }
        public string ApprovedLocationType2 { get; set; }
        public string StockControlNumberFrom2 { get; set; }
        public string StockControlNumberTo2 { get; set; }
        public string ApprovedLocationNumericCode2 { get; set; }
        public string ApprovedLocationType3 { get; set; }
        public string StockControlNumberFrom3 { get; set; }
        public string StockControlNumberTo3 { get; set; }
        public string SettlementAuthorisationCode3 { get; set; }
        public string DataInputStatusIndicator { get; set; }
        public string ISOCountryCode { get; set; }
        public string VendorISOCountryCode { get; set; }
        public string VendorIdentification { get; set; }
        public string ReservedSpace { get; set; }
    }
}
