//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It05_MonetaryAmounts
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string TransactionNumber { get; set; }
        public string AmountEnteredbyAgent { get; set; }
        public string ReservedSpace { get; set; }
        public string TaxMiscellaneousFeeType { get; set; }
        public string TaxMiscellaneousFeeAmount { get; set; }
        public string TaxMiscellaneousFeeType1 { get; set; }
        public string TaxMiscellaneousFeeAmount1 { get; set; }
        public string TaxMiscellaneousFeeType2 { get; set; }
        public string TaxMiscellaneousFeeAmount2 { get; set; }
        public string TicketDocumentAmount { get; set; }
        public string CurrencyType { get; set; }
        public string TaxonCommissionAmount { get; set; }
        public string ReservedSpace1 { get; set; }
        public string TaxMiscellaneousFeeType3 { get; set; }
        public string TaxMiscellaneousFeeAmount3 { get; set; }
        public string TaxMiscellaneousFeeType4 { get; set; }
        public string TaxMiscellaneousFeeAmount4 { get; set; }
        public string TaxMiscellaneousFeeType5 { get; set; }
        public string TaxMiscellaneousFeeAmount5 { get; set; }
        public string CommissionType { get; set; }
        public string CommissionRate { get; set; }
        public string CommissionAmount { get; set; }
        public string CommissionType1 { get; set; }
        public string CommissionRate1 { get; set; }
        public string CommissionAmount1 { get; set; }
        public string CommissionType2 { get; set; }
        public string CommissionRate2 { get; set; }
        public string CommissionAmount2 { get; set; }
        public string NetReportingIndicator { get; set; }
        public string AmountPaidbyCustomer { get; set; }
        public string TaxonCommissionType { get; set; }
    }
}
