//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It08_FormOfPayment
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string TransactionNumber { get; set; }
        public string FormofPaymentAccountNumber { get; set; }
        public string FormofPaymentAmount { get; set; }
        public string ApprovalCode { get; set; }
        public string CurrencyType { get; set; }
        public string ExtendedPaymentCode { get; set; }
        public string FormofPaymentType { get; set; }
        public string ExpiryDate { get; set; }
        public string CustomerFileReference { get; set; }
        public string CreditCardCorporateContract { get; set; }
        public string AddressVerificationCode { get; set; }
        public string SourceofApprovalCode { get; set; }
        public string FormofPaymentTransactionInformation { get; set; }
        public string AuthorisedAmount { get; set; }
        public string FormofPaymentAccountNumber1 { get; set; }
        public string AuthorisedAmount1 { get; set; }
        public string CardVerificationValueResult { get; set; }
        public string CardVerificationValueResult1 { get; set; }
    }
}
