//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It0A_MiscellaneousDocument
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string TransactionNumber { get; set; }
        public string ReasonforIssuanceDescription { get; set; }
        public string BankExchangeRate { get; set; }
        public string InConnectionwithDocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public string AmountinLetters { get; set; }
        public string ReasonforIssuanceCode { get; set; }
        public string MultiplePurposeDocumentOtherCharges { get; set; }
        public string MultiplePurposeDocumentEquivalent { get; set; }
        public string MultiplePurposeDocumentExchangeValue { get; set; }
        public string MultiplePurposeDocumentServiceCharge { get; set; }
        public string MultiplePurposeDocumentTicketTotal { get; set; }
        public string ReservedSpace { get; set; }
    }
}
