//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It0B_AdditionalInformation
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string TransactionNumber { get; set; }
        public string OptionalAgencyAirlineInformation { get; set; }
        public string ReservedSpace { get; set; }
    }
}
