//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It0E_AutomatedTicketAdvice
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string TransactionNumber { get; set; }
        public string PrintLineIdentifier { get; set; }
        public string SponsorInformation { get; set; }
        public string PrintLineIdentifier1 { get; set; }
        public string SponsorInformation1 { get; set; }
        public string PrintLineIdentifier2 { get; set; }
        public string SponsorInformation2 { get; set; }
        public string PrintLineIdentifier3 { get; set; }
        public string SponsorInformation3 { get; set; }
        public string PrintLineIdentifier4 { get; set; }
        public string SponsorInformation4 { get; set; }
        public string PrintLineIdentifier5 { get; set; }
        public string SponsorInformation5 { get; set; }
        public string ReservedSpace { get; set; }
    }
}
