//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class It0Y_AgencyData
    {
        public int Seqno { get; set; }
        public System.Guid UploadGuid { get; set; }
        public string RecordIdentifier { get; set; }
        public string TransactionNumber { get; set; }
        public string AgencyDataAgentUse { get; set; }
        public string AgencyDataReceivingOrderCode { get; set; }
        public string AgencyDataSectionCode { get; set; }
        public string AgencyDataSalesStaffCode { get; set; }
        public string AgencyDataRoutingCode { get; set; }
        public string AgencyDataCustomerCode { get; set; }
        public string AgencyDataPayingInCode { get; set; }
        public string AgencyDataFreeCode { get; set; }
        public string AgencyDataPackageTourCode { get; set; }
        public string AgencyDataRebateCode1 { get; set; }
        public string AgencyDataRebateCode2 { get; set; }
        public string AgencyDataPricingCode { get; set; }
        public string ReservedSpace { get; set; }
        public string CreditCardCompanyDataOrganisationCode { get; set; }
        public string CreditCardCompanyDataOtherExpenseNumber { get; set; }
        public string CreditCardCompanyDataRemarks { get; set; }
        public string CreditCardCompanyDataRemarks1 { get; set; }
        public string CreditCardCompanyDataRemarks2 { get; set; }
        public string CreditCardCompanyDataCardHoldersName { get; set; }
        public string SignedForAmount { get; set; }
        public string CurrencyType { get; set; }
        public string ReservedSpace1 { get; set; }
    }
}
