//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KK_BSP_Batch_Reports_Currency_Conversion
    {
        public string BSP { get; set; }
        public string Period { get; set; }
        public string SourceCurrency { get; set; }
        public string TargetCurrency { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
