//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KK_CodeShareDiscounts
    {
        public int CodeShareNumber { get; set; }
        public string PaxTypeCode { get; set; }
        public int Percentage { get; set; }
        public Nullable<System.DateTime> IssueDateValidFrom { get; set; }
        public Nullable<System.DateTime> IssueDateValidTo { get; set; }
    }
}
