//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KK_CodeShareAgreement
    {
        public string Carrier { get; set; }
        public int CodeShareNumber { get; set; }
        public string PrimeCode { get; set; }
        public string RoutingJourneyATBP { get; set; }
        public string Routing { get; set; }
        public string RoutingValidation { get; set; }
        public string ThirdParty { get; set; }
        public string Revalidation { get; set; }
        public string FIM { get; set; }
        public string InvoluntaryRouting { get; set; }
        public string ValidityType { get; set; }
        public Nullable<System.DateTime> ValidityFrom { get; set; }
        public Nullable<System.DateTime> ValidityTo { get; set; }
        public string ASVAmountExpressed { get; set; }
        public Nullable<decimal> CSCPercentage { get; set; }
        public string IATAClearingHouse { get; set; }
        public string EndorsementBox { get; set; }
        public string FinalShareCompare { get; set; }
        public string ExcludeSAC { get; set; }
    }
}
