//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KK_CustProrateShare
    {
        public string Carrier { get; set; }
        public string Sector { get; set; }
        public decimal Multiplier { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
