//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KK_CodeShare
    {
        public System.Guid RelatedDocumentGuid { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public Nullable<int> CodeShareNumber { get; set; }
        public Nullable<int> Seq { get; set; }
        public string PrevMOS { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public int Discount { get; set; }
        public Nullable<decimal> CSC { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ASVAmount { get; set; }
        public string FinalShareCompare { get; set; }
        public string OwnTicket { get; set; }
        public Nullable<decimal> FinalCodeShareValue { get; set; }
        public Nullable<decimal> FinalShare { get; set; }
        public string AgreementType { get; set; }
        public string Reason { get; set; }
    }
}
