//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class KK_CodeShareASV
    {
        public int CodeShareNumber { get; set; }
        public int Seq { get; set; }
        public string OperatingCarrier { get; set; }
        public string MarketingCarrier { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string ViceVersa { get; set; }
        public string Currency { get; set; }
        public string PrimeCode { get; set; }
        public string Published { get; set; }
        public string RBD { get; set; }
        public string ATBP { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> CSC { get; set; }
        public string Season { get; set; }
        public Nullable<System.DateTime> FlightDateFrom { get; set; }
        public Nullable<System.DateTime> FlightDateTo { get; set; }
        public Nullable<System.DateTime> IssueDateFrom { get; set; }
        public Nullable<System.DateTime> IssueDateTo { get; set; }
        public string SeasonStartDate { get; set; }
        public string SeasonEndDate { get; set; }
        public string AgreementType { get; set; }
        public string AircraftType { get; set; }
    }
}
