//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDM
    {
        public string FlightKey { get; set; }
        public string DestinationCode { get; set; }
        public bool CargoOnlyFlight { get; set; }
        public Nullable<short> Adults { get; set; }
        public Nullable<short> Males { get; set; }
        public Nullable<short> Females { get; set; }
        public Nullable<short> Children { get; set; }
        public Nullable<short> Infants { get; set; }
        public Nullable<int> CabinBaggageWeight { get; set; }
        public string Class1 { get; set; }
        public string Class2 { get; set; }
        public string Class3 { get; set; }
        public Nullable<short> PAX1 { get; set; }
        public Nullable<short> PAX2 { get; set; }
        public Nullable<short> PAX3 { get; set; }
        public Nullable<short> PAD1 { get; set; }
        public Nullable<short> PAD2 { get; set; }
        public Nullable<short> PAD3 { get; set; }
        public Nullable<int> TotalDeadLoad { get; set; }
        public Nullable<int> TotalWeightLoad { get; set; }
    
        public virtual FlightRecord FlightRecord { get; set; }
    }
}
