//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftFormOfPayment2
    {
        public System.Guid LiftHeaderGuid { get; set; }
        public string RecordType { get; set; }
        public string AirlineCode { get; set; }
        public string TicketNumber { get; set; }
        public string CheckDigit { get; set; }
        public string CouponNumber { get; set; }
        public int Seqno { get; set; }
        public string Formofpayment { get; set; }
        public string OldFormofpayment { get; set; }
        public string ApprovedLocationCodeFOP { get; set; }
        public string ApprovedLocationCodeoldFOP { get; set; }
    }
}
