//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftHeaderIndex
    {
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string UsageType { get; set; }
        public string UsageAirline { get; set; }
        public string UsageFlightNumber { get; set; }
        public string UsageOriginCode { get; set; }
        public string UsageDestinationCode { get; set; }
        public string UsedClassofService { get; set; }
        public string SaleOriginCode { get; set; }
        public string SaleDestinationCode { get; set; }
        public string AgencyNumber { get; set; }
        public string SettlementAuthorizationcode { get; set; }
        public System.Guid LiftHeaderGuid { get; set; }
        public System.Guid UploadGuid { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    }
}
