//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid HdrGuid { get; set; }
        public Nullable<System.Guid> SalesUploadGuid { get; set; }
        public Nullable<long> RowId { get; set; }
        public string DocumentNumber { get; set; }
        public string TransactionCode { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string AgentNumericCode { get; set; }
        public string BspIdentifier { get; set; }
        public string IsoCountryCode { get; set; }
        public string ProcessingFileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> RecordCount { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Remarks { get; set; }
    }
}
