//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MadaROE
    {
        public long RECID { get; set; }
        public System.DateTime RoeDate { get; set; }
        public string Seed { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> BUYING { get; set; }
        public Nullable<decimal> SELLING { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
