//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_ApplicabilityStatus
    {
        public System.Guid HdrGuid { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public string DocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string BillingType { get; set; }
        public string Carrier { get; set; }
        public string OriginCityCode { get; set; }
        public string DestinationCityCode { get; set; }
        public string ReservationBookingDesignator { get; set; }
        public string FareAndPassengerTypeCodeDiscount { get; set; }
        public Nullable<int> FareComponent { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string DomesticInternational { get; set; }
        public string FareCategory { get; set; }
        public string FareAndPaxTypeCode { get; set; }
        public string MappedPrimeCode { get; set; }
        public string groupsize { get; set; }
        public string OriginCountryName { get; set; }
        public string DestinationCountryName { get; set; }
        public Nullable<int> SPANumber { get; set; }
        public string Signatory { get; set; }
        public string PrimeCode { get; set; }
        public string PrimeCode_app { get; set; }
        public string FareBasis { get; set; }
        public string FareBasis_app { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> FlightDepartureDate { get; set; }
        public string ValidityofSPA { get; set; }
        public Nullable<System.DateTime> ValidityofSPAFrom { get; set; }
        public Nullable<System.DateTime> ValidityofSPATo { get; set; }
        public string Validity_app { get; set; }
        public string ASVAmountExpressed { get; set; }
        public string SPAExclusiveOfTFCs { get; set; }
        public Nullable<decimal> ISCPercentage { get; set; }
        public string IATAClearingHouse { get; set; }
        public string EndorsementBox { get; set; }
        public string EndorsementBox_app { get; set; }
        public string ThirdPartyInvolvement { get; set; }
        public string ThirdPartyInvolvement_app { get; set; }
        public string RoutingBoth { get; set; }
        public string RoutingJourneyATBP { get; set; }
        public string Routing_app { get; set; }
        public string FlightNumber { get; set; }
        public string Flight_app { get; set; }
        public string ASV_SPAException { get; set; }
        public string ASV_Exist { get; set; }
        public string FareCalculationArea { get; set; }
    }
}
