//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualEntryLog
    {
        public System.Guid HDRGuid { get; set; }
        public string Module { get; set; }
        public string UserId { get; set; }
        public string MachineId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
