//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_DCS_Arrival
    {
        public string AirlineDesignator { get; set; }
        public int FlightNumber { get; set; }
        public string UTCDepartureDate { get; set; }
        public string AirCraftRegistration { get; set; }
    }
}
