//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_UsageVBooking
    {
        public System.Guid Hdrguid { get; set; }
        public string DocumentNumber { get; set; }
        public string CouponNumber { get; set; }
        public bool Validated { get; set; }
        public string ADMNumber { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public string User { get; set; }
        public string IP { get; set; }
        public string Remarks { get; set; }
    }
}
