//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDAgent_ASD
    {
        public string DOM_INT { get; set; }
        public string AgentCode { get; set; }
        public string EnglishName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string FinancialContact { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
    }
}
