//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDITBTHeader
    {
        public string RefContrat { get; set; }
        public Nullable<System.DateTime> On { get; set; }
        public string Entre { get; set; }
        public string GroupName { get; set; }
        public string BookingRef { get; set; }
        public Nullable<int> GroupSize { get; set; }
        public string FareCode { get; set; }
        public string FareBox { get; set; }
        public string FareHT_PAX { get; set; }
        public Nullable<System.DateTime> IssuedOn { get; set; }
        public string Et_And { get; set; }
        public string Currency { get; set; }
        public string TourCode { get; set; }
        public string Information { get; set; }
    }
}
