//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDITBTParcour
    {
        public Nullable<long> RecID { get; set; }
        public string RefContrat { get; set; }
        public string Routing { get; set; }
        public string Carrier { get; set; }
        public string FlightNo { get; set; }
        public string FlightNo1 { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public Nullable<System.DateTime> Dates1 { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> FareAmount { get; set; }
        public string DomInt { get; set; }
    }
}
