//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissingTaxForSectorDetail
    {
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string MappedPrimeCode { get; set; }
        public Nullable<System.DateTime> FlightDepartureDate { get; set; }
        public string DomesticInternational { get; set; }
        public string PassengerType { get; set; }
        public string Tax_FromAirport { get; set; }
        public string DomInt { get; set; }
        public string Tax_MappedPrimeCode { get; set; }
        public string Tax_PassengerType { get; set; }
        public string Tax_DomInt { get; set; }
        public string TaxValidFrom { get; set; }
    }
}
