//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OB_ValidatePrime
    {
        public string RelatedDocumentNumber { get; set; }
        public string AirlineID { get; set; }
        public string MarketingFlightCode { get; set; }
        public string OperatingFlightCode { get; set; }
        public string CouponNumber { get; set; }
        public string ReservationBookingDesignator { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string CouponStatus { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string PM { get; set; }
        public string SPA_Remarks { get; set; }
        public Nullable<decimal> SPA { get; set; }
        public Nullable<decimal> CODESHARE { get; set; }
        public Nullable<decimal> IscPercentage { get; set; }
        public Nullable<decimal> MOV_IscPercentage { get; set; }
        public Nullable<decimal> FinalShare { get; set; }
        public Nullable<decimal> MOV_FinalShare { get; set; }
        public string ProrationErrorMsg { get; set; }
        public Nullable<decimal> MinSectorValue { get; set; }
        public Nullable<decimal> MaxSectorValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Validate { get; set; }
        public string User { get; set; }
        public string IP { get; set; }
        public string SAC { get; set; }
        public Nullable<decimal> CodeShareValue { get; set; }
        public string CodeShareType { get; set; }
        public string CodeShareReason { get; set; }
        public string UserMethodology { get; set; }
    }
}
