//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardBillingTax1
    {
        public string ALC { get; set; }
        public string DOC { get; set; }
        public string CPN { get; set; }
        public string CHK { get; set; }
        public string TAX { get; set; }
        public Nullable<decimal> TAXAMT { get; set; }
        public string BillingPeriod { get; set; }
        public string ManualFlag { get; set; }
    }
}
