//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnExchange
    {
        public string Original_Document_Number { get; set; }
        public string Ex_Doc { get; set; }
        public string Initial_Origin { get; set; }
        public string Initial_Carrier { get; set; }
        public string Initial_Destination { get; set; }
        public Nullable<decimal> FinalShare { get; set; }
        public string Original_Fare_Calculation { get; set; }
        public string New_Fare_Calculation { get; set; }
    }
}
