//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public System.Guid UPLOADID { get; set; }
        public System.Guid LiftHeaderGuid { get; set; }
        public string RecordType { get; set; }
        public string Frequentflyerprogram { get; set; }
        public string Cardnumber { get; set; }
        public string Passengername { get; set; }
        public string Filler1 { get; set; }
        public string Coupon { get; set; }
        public string Ticket { get; set; }
        public string Checkdigit { get; set; }
        public string PNRlocator { get; set; }
        public string Flightdate { get; set; }
        public string Airportoforigin { get; set; }
        public string Marketingcompany { get; set; }
        public string Flightnumber1 { get; set; }
        public string Suffix1 { get; set; }
        public string Airportofdestination { get; set; }
        public string RBD_TKTreservationclass { get; set; }
        public string Serviceclass { get; set; }
        public string Realtimeofdeparture { get; set; }
        public string Realtimeofarrival { get; set; }
        public string Electronicticketing { get; set; }
        public string Upgradingwithpoints { get; set; }
        public string Carrier { get; set; }
        public string Flightnumber2 { get; set; }
        public string Suffix2 { get; set; }
        public string Billablecompany { get; set; }
        public string Filler2 { get; set; }
        public string Filler3 { get; set; }
        public string IdentificationofFF { get; set; }
        public string Flownreservationclass { get; set; }
        public string Passengerindicator { get; set; }
        public string Filler4 { get; set; }
        public string Autocheck_inindicator { get; set; }
        public string TKNA_TKNMindicator { get; set; }
        public string Saleschannelcode { get; set; }
        public string Residentindicator { get; set; }
        public string Filler5 { get; set; }
        public string Filler6 { get; set; }
        public string Autochek_inairport { get; set; }
        public string Accumulates_redeemspoints { get; set; }
        public string Refusedtoboardingcode { get; set; }
        public string FIMCode { get; set; }
        public string FIMcompany { get; set; }
        public string Numberofpassengers { get; set; }
        public string Filler7 { get; set; }
        public string TKTissuedate { get; set; }
        public string ESAC { get; set; }
    }
}
