//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaxAgencyDetail
    {
        public string AgencyNumericCode { get; set; }
        public string TypesofNumeration { get; set; }
        public decimal Rate { get; set; }
        public decimal Level { get; set; }
        public string Applicability { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
