//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_AddOn
    {
        public long ID { get; set; }
        public string CityAirport { get; set; }
        public Nullable<decimal> AddOn { get; set; }
        public string DomInt { get; set; }
    }
}
