//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLBDetail
    {
        public string AgentNumericCode { get; set; }
        public string FinancialYear { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> PLBRange { get; set; }
        public decimal PLBPercentage { get; set; }
        public Nullable<decimal> Split { get; set; }
        public Nullable<decimal> PLBAmount { get; set; }
    }
}
