//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlusUp
    {
        public long RecId { get; set; }
        public string FareComponent { get; set; }
        public string FromSector { get; set; }
        public string Carrier { get; set; }
        public string ToSector { get; set; }
        public Nullable<decimal> PlusUp1 { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
    }
}
