//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMPBaseAmount
    {
        public string OrgCity { get; set; }
        public string OrgCountry { get; set; }
        public string Currency { get; set; }
        public string DestCity { get; set; }
        public string DestCountry { get; set; }
        public string Carrier { get; set; }
        public string Type { get; set; }
        public string BaseAmount { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
    }
}
