//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNL
    {
        public long PNLID { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FlightNo { get; set; }
        public string SectorFrom { get; set; }
        public string SectorTo { get; set; }
        public string Unk { get; set; }
        public Nullable<double> ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Adult { get; set; }
        public string Child { get; set; }
        public string Infant { get; set; }
        public string TicketNumber { get; set; }
        public string Class { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string VIA { get; set; }
        public Nullable<int> Validated { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string CouponStatus { get; set; }
        public Nullable<System.DateTime> FlightDepartureDate { get; set; }
        public Nullable<int> FlightNumber { get; set; }
        public Nullable<long> HEADERPNLID { get; set; }
    }
}
