//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNL1
    {
        public string FileName { get; set; }
        public string Carrier { get; set; }
        public string FlightNo { get; set; }
        public System.DateTime FlightDate { get; set; }
        public string Origin { get; set; }
        public string CFG { get; set; }
        public string Destination { get; set; }
        public string NoofPax { get; set; }
        public string Class { get; set; }
        public string PaxName { get; set; }
        public string TicketNo { get; set; }
        public string CpnNo { get; set; }
        public string Identification { get; set; }
        public string Infant { get; set; }
        public string InfTicketNo { get; set; }
        public string InfCpnNo { get; set; }
    }
}
