//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PNLFileUploadStatu
    {
        public long RecordId { get; set; }
        public System.Guid UploadId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public Nullable<decimal> Ticket { get; set; }
        public Nullable<decimal> Coupons { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> LoadedTickets { get; set; }
        public Nullable<decimal> LoadedCoupons { get; set; }
        public Nullable<decimal> LoadedTaxes { get; set; }
    }
}
