//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prime
    {
        public System.Guid PrimeGuid { get; set; }
        public int OrganizationID { get; set; }
        public int ChargeCode { get; set; }
        public int DetailNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceDate { get; set; }
        public decimal GrossBilled { get; set; }
        public string AddOnChargeName { get; set; }
        public Nullable<int> AddOnChargePercentage { get; set; }
        public Nullable<decimal> AddOnChargeAmount { get; set; }
        public Nullable<decimal> TotalNetAmount { get; set; }
        public Nullable<long> TicketOrFIMIssuingAirline { get; set; }
        public Nullable<int> TicketOrFIMCouponNumber { get; set; }
        public string TicketDocOrFIMNumber { get; set; }
        public Nullable<int> CheckDigit { get; set; }
        public string CurrAdjustmentIndicator { get; set; }
        public string ElectronicTicketIndicator { get; set; }
        public string AirlineFlightDesignator { get; set; }
        public string FlightNo { get; set; }
        public string FlightDate { get; set; }
        public string FromAirportCode { get; set; }
        public string ToAirportCode { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public string BatchSequenceNum { get; set; }
        public string CurrencyCode { get; set; }
        public string ClearanceCurrencyCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string SettlementMonthPeriod { get; set; }
        public string SettlementMethod { get; set; }
        public Nullable<decimal> UatpAmount { get; set; }
        public Nullable<byte> Processed { get; set; }
        public Nullable<System.Guid> ProrateGuid { get; set; }
        public string NewInvoiceNumber { get; set; }
        public Nullable<System.Guid> UploadGuid { get; set; }
    }
}
