//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRORATEDTRANSACTION
    {
        public System.Guid ProrateGuid { get; set; }
        public System.Guid HeaderGuid { get; set; }
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
        public string ProrationFlag { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public string SectorOrigin { get; set; }
        public string SectorDestination { get; set; }
        public string SectorCarrier { get; set; }
        public string Currency { get; set; }
        public decimal FinalShare { get; set; }
        public int CouponNumber { get; set; }
        public Nullable<decimal> Roe { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string Carrier { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string ReservationBookingDesignator { get; set; }
        public string UsageAirline { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string UsageFlightNumber { get; set; }
        public string UsageOriginCode { get; set; }
        public string UsageDestinationCode { get; set; }
        public string UsedClassofService { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public string CouponStatus { get; set; }
        public string AccountingStatus { get; set; }
        public Nullable<bool> AccountingOnEstimate { get; set; }
        public string BillingStatus { get; set; }
        public string AgentNumericCode { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string PassengerName { get; set; }
        public string TransactionCode { get; set; }
        public string DocumentType { get; set; }
        public string FormofPaymentType { get; set; }
        public string CustomerFileReference { get; set; }
        public string BookingReference { get; set; }
        public string CntryOrg { get; set; }
        public string CntryDes { get; set; }
        public string DomInt { get; set; }
        public string PaxReferences { get; set; }
    }
}
