//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProrateStep
    {
        public System.Guid HdrGuid { get; set; }
        public string Fctbp { get; set; }
        public Nullable<decimal> FareInNuc { get; set; }
        public Nullable<decimal> Roe { get; set; }
        public string AtbpFare { get; set; }
        public string EfpFdrpMosOrBsrBbr { get; set; }
        public string AtbpEquivalentFarePaid { get; set; }
        public Nullable<decimal> UsdFdr { get; set; }
        public string AtbpUsd { get; set; }
        public string TotalProvisoUsd { get; set; }
        public string BtbpUsd { get; set; }
        public Nullable<long> TotalProrateFactors { get; set; }
        public Nullable<decimal> Quotient { get; set; }
        public Nullable<decimal> Mpr { get; set; }
        public Nullable<decimal> ResidualValue { get; set; }
        public Nullable<bool> AttachmentA { get; set; }
        public Nullable<bool> AttachmentB { get; set; }
        public Nullable<bool> Reversed { get; set; }
        public string FareComponent { get; set; }
    }
}
