//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProrationException
    {
        public Nullable<System.DateTime> DateProcess { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public string DocumentNumber { get; set; }
        public string FareCalculationArea { get; set; }
        public decimal CouponNumber { get; set; }
        public string CouponStatus { get; set; }
        public string Fare { get; set; }
        public string EquivalentFare { get; set; }
        public string ErrorMsg { get; set; }
    }
}
