//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefTaxSurComSum
    {
        public string RelatedDocumentNumber { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Surcharges { get; set; }
        public Nullable<decimal> Commission { get; set; }
    }
}
