//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repgroup
    {
        public System.DateTime SchDPDT { get; set; }
        public string AirlineCode { get; set; }
        public string FlightNumber { get; set; }
        public string OrigAirport { get; set; }
        public string DestAirport { get; set; }
        public string ReportingGroupName { get; set; }
        public string ReportingGroupCode { get; set; }
    }
}
