//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsCustomization
    {
        public byte[] AirlineLogo { get; set; }
        public string AirlineName { get; set; }
        public string ReportingHeaderText { get; set; }
        public string ReportingFooterText { get; set; }
        public string ReportHeaderTextColor { get; set; }
        public string ColumnHeaderTextColor { get; set; }
        public string ColumnHeaderBackColor { get; set; }
        public string HeaderTextColor { get; set; }
        public string FooterTextColor { get; set; }
    }
}
