//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsCustomised
    {
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public string ReportDescription { get; set; }
        public string ReportCategoryCode { get; set; }
        public string ReportFilePath { get; set; }
        public string ReportFileName { get; set; }
        public string ReportParameterScreen { get; set; }
        public Nullable<int> ReportOrder { get; set; }
    
        public virtual ReportsCategory ReportsCategory { get; set; }
    }
}
