//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class rjUserTaxChanx
    {
        public System.Guid IdGuid { get; set; }
        public Nullable<System.Guid> RjGuid { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> OALBilled { get; set; }
        public Nullable<decimal> OWNAccepted { get; set; }
        public Nullable<decimal> TaxAdj { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string InvoiceNumber { get; set; }
    }
}
