//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Area { get; set; }
        public int Route1 { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Via { get; set; }
    }
}
