//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRelatedDocumentInformation2
    {
        public System.Guid RelatedDocumentGuid { get; set; }
        public System.Guid HdrGuid { get; set; }
        public string DocumentNumber { get; set; }
        public string CheckDigit { get; set; }
        public Nullable<bool> IsConjunction { get; set; }
        public Nullable<bool> IsReissue { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public string RelatedTicketCheckDigit { get; set; }
        public string CouponIndicator { get; set; }
        public string TransactionCode { get; set; }
        public string TransmissionControlNumber { get; set; }
        public Nullable<System.Guid> SalesUploadGuid { get; set; }
        public Nullable<System.Guid> LiftUploadGuid { get; set; }
        public string SequenceNumber { get; set; }
    }
}
