//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDocumentPayment2
    {
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string ApprovalCode { get; set; }
        public string ExtendedPaymentCode { get; set; }
        public string FormofPaymentType { get; set; }
        public string ExpiryDate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CustomerFileReference { get; set; }
        public string CreditCardCorporateContract { get; set; }
        public string AddressVerificationCode { get; set; }
        public string SourceofApprovalCode { get; set; }
        public string TransactionInformation { get; set; }
        public Nullable<decimal> AuthorisedAmount { get; set; }
        public string AccountNumber1 { get; set; }
        public Nullable<decimal> AuthorisedAmount1 { get; set; }
        public string CardVerificationValueResult { get; set; }
        public string CardVerificationValueResult1 { get; set; }
        public Nullable<decimal> SignedforAmount { get; set; }
        public Nullable<decimal> RemittanceAmount { get; set; }
        public string RemittanceCurrency { get; set; }
        public string TransactionCode { get; set; }
        public Nullable<System.Guid> HdrGuidRef { get; set; }
        public string DocumentNumber { get; set; }
        public string TransactionCode2 { get; set; }
        public string RelatedDocumentNumber { get; set; }
    }
}
