//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDocumentAdditionalInfo
    {
        public System.Guid HdrGuid { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string TransactionCode { get; set; }
        public string FileTypeVersion { get; set; }
        public Nullable<System.DateTime> FileProcessingDate { get; set; }
        public string FileProcessingTime { get; set; }
        public string TransactionNumber { get; set; }
        public string SequenceNumber { get; set; }
        public Nullable<System.DateTime> BillingAnalysisEndingDate { get; set; }
        public string BillingAnalysisMonth { get; set; }
        public string BSPIdentifier { get; set; }
        public Nullable<System.DateTime> ReportingEndDate { get; set; }
        public Nullable<System.Guid> OriginalIssueGuid { get; set; }
        public string PreviousIssueDocumentNumber { get; set; }
        public Nullable<System.Guid> PreviousIssueGuid { get; set; }
        public Nullable<System.DateTime> LastProrationDate { get; set; }
        public string IsoCountryCode { get; set; }
        public string DataSource { get; set; }
        public Nullable<System.Guid> SalesUploadGuid { get; set; }
    }
}
