//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public System.Guid HdrGuid { get; set; }
        public Nullable<bool> Validated { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public string ValidatedBy { get; set; }
        public Nullable<bool> Exported { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string ExportedBy { get; set; }
    }
}
