//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReport
    {
        public string DocumentNumber { get; set; }
        public string AgentNumericCode { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string FareCurrency { get; set; }
        public Nullable<decimal> EquivalentFare { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string TotalCurrency { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionGroup { get; set; }
        public string PaxType { get; set; }
        public Nullable<decimal> AccountCollected { get; set; }
        public string AmountCollectedCurrency { get; set; }
        public Nullable<decimal> taxCollected { get; set; }
        public Nullable<decimal> SurchargeCollected { get; set; }
        public Nullable<decimal> CommissionCollected { get; set; }
        public Nullable<decimal> FareCollected { get; set; }
        public string BspIdentifier { get; set; }
        public string IsoCountryCode { get; set; }
        public string ExchangeADC { get; set; }
        public string ITBT { get; set; }
        public string OriginalIssueDocumentNumber { get; set; }
        public string DocumentType { get; set; }
        public string TicketDocumentAmount { get; set; }
        public string CommissionableAmount { get; set; }
        public string OtherAmountRate { get; set; }
        public string DocumentAmountType { get; set; }
        public string OtherAmountCode { get; set; }
        public string OtherAmount { get; set; }
        public string CurrencyType { get; set; }
        public Nullable<decimal> FOPAMOUNT { get; set; }
        public string Currency { get; set; }
        public string FormofPaymentType { get; set; }
        public Nullable<decimal> Remittance { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> CommissionPercentage { get; set; }
    }
}
