//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCouponDetail
    {
        public string DocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string Sector { get; set; }
        public string Carrier { get; set; }
        public string StopOverCode { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string FrequentFlyerReference { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> FlightDepartureDate { get; set; }
        public string FlightDepartureTime { get; set; }
        public Nullable<System.DateTime> NotValidBefore { get; set; }
        public Nullable<System.DateTime> NotValidAfter { get; set; }
        public string ReservationBookingDesignator { get; set; }
        public string FreeBaggageAllowance { get; set; }
        public string FlightBookingStatus { get; set; }
        public string OriginAirportCityCode1 { get; set; }
        public string StopoverCode1 { get; set; }
        public string OriginAirportCityCode2 { get; set; }
        public string StopoverCode2 { get; set; }
        public string SegmentIdentifier { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
    }
}
