//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCouponTaxInformation
    {
        public string DocumentNumber { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string CouponTaxCode { get; set; }
        public string CouponTaxReportedCurrency { get; set; }
        public Nullable<decimal> CouponTaxReportedAmount { get; set; }
        public string CouponTaxCurrency { get; set; }
        public Nullable<decimal> CouponTaxApplicableAmount { get; set; }
        public string CouponTaxAirportCode { get; set; }
        public string SegmentTaxAirportCode { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string SegmentIdentifier { get; set; }
        public System.Guid HdrGuidRef { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public int SequenceNumber { get; set; }
        public long FileSequence { get; set; }
    
        public virtual SalesDocumentCoupon SalesDocumentCoupon { get; set; }
    }
}
