//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCode
    {
        public string ServiceCode1 { get; set; }
        public string RFIC { get; set; }
        public string RFISC { get; set; }
        public string ServiceElement { get; set; }
        public string ServiceName { get; set; }
    }
}
