//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLSLDMPaxAdjust
    {
        public string FlightNumber { get; set; }
        public System.DateTime FlightDepartureDate { get; set; }
        public string FlightDepartureTime { get; set; }
        public Nullable<int> LDMPaxCountAdjust { get; set; }
        public Nullable<int> SLSPaxCountAdjust { get; set; }
    }
}
