//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLSPaxCount
    {
        public string FlightKey { get; set; }
        public string DestinationCode { get; set; }
        public string ClassOfService { get; set; }
        public Nullable<int> TotalRevPax { get; set; }
        public Nullable<int> TotalRevAdultsPax { get; set; }
        public Nullable<int> TotalRevChildrenPax { get; set; }
        public Nullable<int> TotalRevMalesPax { get; set; }
        public Nullable<int> TotalRevFemalesPax { get; set; }
        public Nullable<int> TotalNonRevPax { get; set; }
        public Nullable<int> TotalNonRevInfants { get; set; }
    
        public virtual SL SL { get; set; }
    }
}
