//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnapBulletin
    {
        public int BulletinNumber { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string OpeningNo { get; set; }
        public string ClosingNo { get; set; }
        public long Qty { get; set; }
        public string CountryCode { get; set; }
        public System.DateTime Date { get; set; }
        public string OP { get; set; }
    }
}
