//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPAException
    {
        public int SPANumber { get; set; }
        public string ApplicableExclude { get; set; }
        public Nullable<int> Seq { get; set; }
        public string RowRelation { get; set; }
        public string Element { get; set; }
        public string JAPS { get; set; }
        public string WO { get; set; }
        public string RegionType { get; set; }
        public string Region { get; set; }
        public string ProvisoApplicability { get; set; }
        public string RegionTypeBF { get; set; }
        public string RegionBF { get; set; }
        public string RegionTypeAT { get; set; }
        public string RegionAT { get; set; }
        public string FareCategory { get; set; }
        public string PrimeCode { get; set; }
        public string FareAndPaxTypeCode { get; set; }
        public string FareBasis { get; set; }
    }
}
