//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRD86SurrenderedTicketDocIden
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string Filler { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string DateofIssue { get; set; }
        public string AgencyCodeNumber { get; set; }
        public string Filler1 { get; set; }
        public string SystemProviderIdentifier { get; set; }
        public string CouponUseIndicator { get; set; }
        public string ConjunctionCompanionTicketIndicator { get; set; }
        public string ElectronicTicketIndicator { get; set; }
        public string InternationalSaleIndicator { get; set; }
        public string TourCode { get; set; }
        public string AirportCityCodeTrueOrigin { get; set; }
        public string AirportCityCodeTrueDestination { get; set; }
        public string PNRReferenceandorAirlineData { get; set; }
        public string DocumentType { get; set; }
        public string Filler2 { get; set; }
    }
}
