//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRD90SurrenderedItinerary
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string Filler { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string CouponNumberSegmentIdentifier { get; set; }
        public string StopoverCode { get; set; }
        public string AirportCityCodeOrigin { get; set; }
        public string ReservedSpace1 { get; set; }
        public string AirportCityCodeDestination { get; set; }
        public string ReservedSpace2 { get; set; }
        public string CarrierCode { get; set; }
        public string ReservedSpace3 { get; set; }
        public string Filler1 { get; set; }
        public string FlightNumber { get; set; }
        public string ReservationsBookingDesignator { get; set; }
        public string FlightDate { get; set; }
        public string FlightDepartureTime { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string Filler2 { get; set; }
    }
}
