//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surcharge
    {
        public string Carrier { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string SectorType { get; set; }
        public string SurchargeCode { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
    }
}
