//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemCheck
    {
        public System.DateTime BatchID { get; set; }
        public string Operation { get; set; }
        public string CalledFrom { get; set; }
        public Nullable<System.DateTime> DateChecked { get; set; }
    }
}
