//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public string UserId { get; set; }
        public string UserHash { get; set; }
        public string UserSalt { get; set; }
        public Nullable<bool> UserStatus { get; set; }
        public Nullable<byte> UserSecurityLevel { get; set; }
        public Nullable<System.DateTime> UserPwdExpiry { get; set; }
        public string UserModifyBy { get; set; }
        public Nullable<System.DateTime> UserModifyDate { get; set; }
    }
}
