//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableIndexScriptBak_02SEP2015
    {
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public string DropIndexScript { get; set; }
        public string DropPKIndexScript { get; set; }
        public string DropFKIndexScript { get; set; }
        public string DropStatScript { get; set; }
        public string CreateIndexScript { get; set; }
        public string CreatePKIndexScript { get; set; }
        public string CreateFKIndexScript { get; set; }
        public string CreateStatScript { get; set; }
    }
}
