//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDef_Document_BSP_Period
    {
        public System.Guid UploadGuid { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<System.DateTime> FileHotReportingEndDate { get; set; }
        public Nullable<System.DateTime> BillingAnalysisEndingDate { get; set; }
        public string BillingAnalysisMonth { get; set; }
        public Nullable<int> Period { get; set; }
        public string BspIdentifier { get; set; }
        public string TransactionCode { get; set; }
        public string LoadSortOrder { get; set; }
        public string FileType { get; set; }
    }
}
