//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax1
    {
        public System.Guid UploadId { get; set; }
        public string RecordId { get; set; }
        public Nullable<System.Guid> HDRGUID { get; set; }
        public string Ticket { get; set; }
        public string TaxCode { get; set; }
        public string TaxCur { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
    }
}
