//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Additional
    {
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public string MappedPrimeCode { get; set; }
        public string PassengerType { get; set; }
        public string DomInt { get; set; }
        public Nullable<int> TransitDuration { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string TaxCode { get; set; }
        public string TaxCurrency { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public string OwnAirline { get; set; }
        public string BilledAirline { get; set; }
    }
}
