//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxLibrary
    {
        public System.Guid HdrGuid { get; set; }
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
        public string TransactionCode { get; set; }
        public string ExchangeADC { get; set; }
        public string ITBT { get; set; }
        public string OriginalIssueDocumentNumber { get; set; }
        public string DocumentType { get; set; }
        public string TicketDocumentAmount { get; set; }
        public string CommissionableAmount { get; set; }
        public string OtherAmountRate { get; set; }
        public string DocumentAmountType { get; set; }
        public string OtherAmountCode { get; set; }
        public string OtherAmount { get; set; }
        public string CurrencyType { get; set; }
    }
}
