//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class template1
    {
        public System.Guid HOT_UploadGuid { get; set; }
        public string HOT_TransactionNumber { get; set; }
        public string PaxDocumentNumber { get; set; }
        public Nullable<System.Guid> UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string FormofPaymentType { get; set; }
        public string FormofPaymentAmount { get; set; }
        public string FormofPaymentAccountNumber { get; set; }
        public string ExpiryDate { get; set; }
        public string ApprovalCode { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceDate { get; set; }
        public string SignedforAmount { get; set; }
        public string RemittanceAmount { get; set; }
        public string CurrencyType1 { get; set; }
        public string CardVerificationValueResult { get; set; }
        public string CurrencyType2 { get; set; }
    }
}
