//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFC
    {
        public System.Guid TfcGuid { get; set; }
        public string TfcCode { get; set; }
        public string TfcType { get; set; }
        public string TfcCountry { get; set; }
        public string TfcName { get; set; }
        public Nullable<System.DateTime> TfcValidFrom { get; set; }
        public Nullable<System.DateTime> TfcValidTo { get; set; }
        public string TfcDomesticInternational { get; set; }
        public string TfcArrivalDeparture { get; set; }
        public string TfcAirportcode { get; set; }
        public string TfcCitycode { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
