//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFC_MD
    {
        public string OriginAirport { get; set; }
        public string DestinationAirport { get; set; }
        public string ViceVersa { get; set; }
        public string TFC { get; set; }
        public string Currency { get; set; }
        public decimal TFCAmount { get; set; }
        public System.DateTime IssueDateValidFrom { get; set; }
        public System.DateTime IssueDateValidTo { get; set; }
    }
}
