//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFCCollected
    {
        public long RecId { get; set; }
        public string DocumentNumber { get; set; }
        public string TransactionCode { get; set; }
        public string PaxType { get; set; }
        public string Currency { get; set; }
        public string Sector { get; set; }
        public string Country { get; set; }
        public string Dom_Intl { get; set; }
        public Nullable<decimal> IL { get; set; }
        public Nullable<decimal> AP { get; set; }
        public Nullable<decimal> RI { get; set; }
        public Nullable<decimal> UH { get; set; }
        public Nullable<decimal> EX { get; set; }
        public Nullable<decimal> IT { get; set; }
        public Nullable<decimal> MJ { get; set; }
        public Nullable<decimal> HB { get; set; }
        public Nullable<decimal> VT { get; set; }
        public Nullable<decimal> OY { get; set; }
        public Nullable<decimal> DE { get; set; }
        public Nullable<decimal> RA { get; set; }
        public Nullable<decimal> QX { get; set; }
        public Nullable<decimal> IZ { get; set; }
        public Nullable<decimal> FR { get; set; }
        public Nullable<decimal> SI { get; set; }
        public Nullable<decimal> JJ { get; set; }
        public Nullable<decimal> GB { get; set; }
        public Nullable<decimal> UB { get; set; }
        public Nullable<decimal> JD { get; set; }
        public Nullable<decimal> QV { get; set; }
        public Nullable<decimal> YP { get; set; }
        public Nullable<decimal> PT { get; set; }
        public Nullable<decimal> GE { get; set; }
        public Nullable<decimal> JA { get; set; }
        public Nullable<decimal> CJ { get; set; }
        public Nullable<decimal> RN { get; set; }
        public Nullable<decimal> VV { get; set; }
        public Nullable<decimal> OA { get; set; }
        public Nullable<decimal> ZF { get; set; }
        public Nullable<decimal> BG { get; set; }
        public Nullable<decimal> CP { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> Surcharge1 { get; set; }
        public Nullable<decimal> Surcharge2 { get; set; }
        public Nullable<decimal> Surcharge3 { get; set; }
        public Nullable<decimal> Commission1 { get; set; }
        public Nullable<decimal> Commission2 { get; set; }
        public Nullable<decimal> Commission3 { get; set; }
        public Nullable<decimal> TAXCommission1 { get; set; }
        public Nullable<decimal> TAXCommission2 { get; set; }
        public Nullable<decimal> TAXCommission3 { get; set; }
    }
}
