//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketObservation
    {
        public long RecID { get; set; }
        public System.Guid Hdrguid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string UserID { get; set; }
        public string UserIP { get; set; }
        public string Subject { get; set; }
        public byte[] Observation { get; set; }
    }
}
