//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAccounting
    {
        public long TKAccID { get; set; }
        public string AccountingContext { get; set; }
        public string AccountID { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string CurrencyCode { get; set; }
        public string ChargeCode { get; set; }
        public string AmountCode { get; set; }
        public string TicketAirlineID { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string OtherInfo { get; set; }
        public string AccountingPeriod { get; set; }
        public bool InterfaceFlag { get; set; }
    
        public virtual AccountMaster AccountMaster { get; set; }
    }
}
