//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public System.Guid UploadId { get; set; }
        public string FileName { get; set; }
        public string RecordId { get; set; }
        public Nullable<System.Guid> HDRGUID { get; set; }
        public string Ticket1 { get; set; }
        public string ConJunctionTicket { get; set; }
        public string ConJunctionTicketNumber { get; set; }
        public string Carrier { get; set; }
        public string PRN { get; set; }
        public string OriDes { get; set; }
        public string Ori { get; set; }
        public string Des { get; set; }
        public string SI { get; set; }
        public string FareCalculationModeIndicator { get; set; }
        public string PlaceOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string IssueOfficeCode { get; set; }
        public string PaxName { get; set; }
        public string PaxTitle { get; set; }
        public string PaxAgeCat { get; set; }
        public string PaxS { get; set; }
        public string PaxI { get; set; }
        public string FareCurrency { get; set; }
        public Nullable<decimal> FareAmount { get; set; }
        public string EquivaletFareCurrency { get; set; }
        public Nullable<decimal> EqivalentFare { get; set; }
        public Nullable<decimal> BSR { get; set; }
        public string TotalTaxCurrency { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public string TotalCurrency { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string FCA { get; set; }
        public string FORMOFPAYMENT { get; set; }
        public string FAREENDORSABLE { get; set; }
        public string FT { get; set; }
        public string FREQUENTFLYER { get; set; }
        public string NONENDORSABLE { get; set; }
        public string Sac { get; set; }
    }
}
