//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKF81FareCalculation
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string Filler { get; set; }
        public string FareCalculationPricingIndicator { get; set; }
        public string FareCalculationSequenceNumber { get; set; }
        public string FareCalculationArea { get; set; }
        public string Filler1 { get; set; }
    }
}
