//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKS30FareTaxAmounts
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string FareAmount { get; set; }
        public string CurrencyType { get; set; }
        public string DecimalPlacesCurrencyType { get; set; }
        public string Filler { get; set; }
        public string TaxMiscellaneousFeeType1 { get; set; }
        public string TaxMiscellaneousFeeSubCode1 { get; set; }
        public string TaxMiscellaneousFeeAmount1 { get; set; }
        public string TaxMiscellaneousFeeType2 { get; set; }
        public string TaxMiscellaneousFeeSubCode2 { get; set; }
        public string TaxMiscellaneousFeeAmount2 { get; set; }
        public string TicketDocumentAmount { get; set; }
        public string InternationalFareAmount { get; set; }
        public string SourceofTotalAmount { get; set; }
        public string SourceofTaxBreakdown { get; set; }
        public string Filler1 { get; set; }
        public string CurrencyTypeInternationalFare { get; set; }
        public string DecimalPlacesCurrencyofInternationalFare { get; set; }
        public string PTAMultiPersonCount { get; set; }
        public string PenaltyRestrictionIndicator { get; set; }
    }
}
