//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKS39CommissionAmounts
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string StatisticalCode { get; set; }
        public string Filler { get; set; }
        public string CommissionType1 { get; set; }
        public string CommissionRate1 { get; set; }
        public string CommissionAmount1 { get; set; }
        public string CommissionType2 { get; set; }
        public string CommissionRate2 { get; set; }
        public string CommissionAmount2 { get; set; }
        public string EffectiveCommissionRate { get; set; }
        public string EffectiveCommissionAmount { get; set; }
        public string RemittanceAmount { get; set; }
        public string ElectronicSettlementAuthorizationCode { get; set; }
        public string Filler1 { get; set; }
        public string BookingAgentIdentification { get; set; }
    }
}
