//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKS45OriginalIssueInfo
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string ReportPeriod { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string TicketingCarrierCodeOriginalIssue { get; set; }
        public string TicketDocumentNumberOriginalIssue { get; set; }
        public string ReservedSpace1 { get; set; }
        public string CheckDigitOriginalIssueTicketDocumentNumber { get; set; }
        public string ReferenceNumberAADOriginalNumber { get; set; }
        public string TicketDocumentAmountAADCorrect { get; set; }
        public string TicketDocumentAmountExchangeDocumentTotal { get; set; }
        public string TicketDocumentAmountExchangeOriginalorFareAmountAADCorrectOriginal { get; set; }
        public string CommissionRateAADCorrect { get; set; }
        public string CommissionAmountAADCorrect { get; set; }
        public string AADCorrectTaxAmount { get; set; }
        public string RemittanceAmountAADCorrect { get; set; }
        public string Filler { get; set; }
    }
}
