//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKT06TransactionHeader
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string Filler { get; set; }
        public string TransactionNumber { get; set; }
        public string ReferenceNumber { get; set; }
        public string BoxBatch { get; set; }
        public string BoxBatchSequenceNumber { get; set; }
        public string InvoiceSequenceNumber { get; set; }
        public string Filler1 { get; set; }
        public string TransactionRecordCounter { get; set; }
        public string Filler2 { get; set; }
        public string AuditStatusIndicator { get; set; }
        public string CarrierCode { get; set; }
        public string ReservedSpace { get; set; }
        public string Filler3 { get; set; }
        public string SystemProviderIdentifier { get; set; }
        public string TicketingModeIndicator { get; set; }
        public string TransactionDateTime { get; set; }
        public string Filler4 { get; set; }
    }
}
