//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP66EMDCouponValue
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string CouponNumber { get; set; }
        public string CouponValue { get; set; }
        public string NonRefundableIndicator { get; set; }
        public string NonCommissionableIndicator { get; set; }
        public string Remarks { get; set; }
        public string NonReissueableNonExchangeableIndicator { get; set; }
        public string ConsumedAtIssuanceIndicator { get; set; }
        public string AdditionalServicesNumberofServicesFees { get; set; }
        public string Filler { get; set; }
    }
}
