//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP67EMDInConnectionWithCoupon
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketingCarrierCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string ReservedSpace { get; set; }
        public string CheckDigitTicketDocumentNumber { get; set; }
        public string CouponNumber { get; set; }
        public string PresentTo { get; set; }
        public string CouponNumberInConnectionWith { get; set; }
        public string TicketingCarrierCodeInConnectionWith { get; set; }
        public string TicketDocumentNumberInConnectionWith { get; set; }
        public string ReservedSpace1 { get; set; }
        public string CheckDigitInConnectionWith { get; set; }
        public string BaggageAllowance { get; set; }
        public string CurrencyTypeBaggageRate { get; set; }
        public string BaggageRate { get; set; }
        public string BaggageQuantity { get; set; }
        public string Filler { get; set; }
    }
}
