//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_BSP_BATCH_REPORTS_KK_Step1
    {
        public string BSP { get; set; }
        public string BillingMonth { get; set; }
        public Nullable<int> Period { get; set; }
        public string source { get; set; }
        public string RFNDTicket { get; set; }
        public string TicketNo { get; set; }
        public string IssueDate { get; set; }
        public string Route_Full { get; set; }
        public string Cpn_Route { get; set; }
        public int CouponNumber { get; set; }
        public string Currency { get; set; }
        public decimal Rate { get; set; }
        public Nullable<decimal> COMM { get; set; }
        public string Country_Origin { get; set; }
        public string Country_Destination { get; set; }
        public string LINES { get; set; }
        public Nullable<decimal> Cpn_ProShare { get; set; }
        public Nullable<decimal> Cpn_Tax { get; set; }
        public Nullable<decimal> Cpn_Total { get; set; }
        public string Cpn_FlightNo { get; set; }
        public string Cpn_FlightDate { get; set; }
        public string FOP { get; set; }
        public string FormOfPayment { get; set; }
        public string ARC { get; set; }
        public string LoadSortOrder { get; set; }
    }
}
