//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_BSP_SAP_LINK_HEADER_KK
    {
        public string BSP { get; set; }
        public string BillingMonth { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> Records { get; set; }
        public Nullable<long> LastID { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    }
}
