//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_BSP_SAP_Flown_Data_Transfer_KK
    {
        public Nullable<long> Id { get; set; }
        public string Zzislem { get; set; }
        public string Zzkasa { get; set; }
        public string ZzhatType { get; set; }
        public string Zzdest { get; set; }
        public string Bldat { get; set; }
        public string Budat { get; set; }
        public string Blart { get; set; }
        public string Bukrs { get; set; }
        public string Gjahr { get; set; }
        public string Waers { get; set; }
        public string Lifnr { get; set; }
        public Nullable<decimal> Wrbtr { get; set; }
        public string Sgtxt { get; set; }
        public string Zzbutce { get; set; }
        public string Zzhat1 { get; set; }
        public string Zzhat2 { get; set; }
        public string Zzucusn { get; set; }
        public string Zztarih { get; set; }
        public string BSP { get; set; }
        public System.DateTime UsageDate { get; set; }
        public string Period { get; set; }
        public string LoadSortOrder { get; set; }
    }
}
