//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_BSP_BATCH_REPORTS_KK_Step2
    {
        public string BSP { get; set; }
        public string BillingMonth { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<System.DateTime> BillingAnalysisEndingDate { get; set; }
        public string TransType { get; set; }
        public string FormOfPayment { get; set; }
        public string LINES { get; set; }
        public string Item { get; set; }
        public string KDV { get; set; }
        public Nullable<decimal> AmountWithVAT { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountCode { get; set; }
        public string Currency { get; set; }
        public string sap_period_desc { get; set; }
    }
}
