//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOH03SalesReportHeader
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string AgencyCodeNumber { get; set; }
        public string ReportPeriod { get; set; }
        public string ProcessingDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string BoxBatch { get; set; }
        public string Filler { get; set; }
        public string CurrencyType { get; set; }
        public string Filler1 { get; set; }
    }
}
