//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToleranceValue
    {
        public string RecordID { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
