//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsData
    {
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string SalesPeriod { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string TransactionCode { get; set; }
        public string DocumentType { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string FormofPaymentType { get; set; }
        public Nullable<decimal> Receivable { get; set; }
        public Nullable<decimal> Payable { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string FareCurrency { get; set; }
        public Nullable<decimal> EquivalentFare { get; set; }
        public string TotalCurrency { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string BookingReference { get; set; }
        public string InvoiceNumber { get; set; }
        public string CustomerFileReference { get; set; }
        public string PassengerName { get; set; }
        public string AccountNumber1 { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public Nullable<System.Guid> HdrGuidRef { get; set; }
        public string DocumentNumber { get; set; }
        public string TransactionCode2 { get; set; }
        public Nullable<bool> SalesDataAvailable { get; set; }
        public string AccountingStatus { get; set; }
        public Nullable<bool> ProratedFlag { get; set; }
        public Nullable<bool> FBSFlag { get; set; }
    }
}
