//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trigger_Log
    {
        public string TriggerName { get; set; }
        public Nullable<System.Guid> HdrGuid { get; set; }
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
        public Nullable<System.Guid> Inserted_HdrGuid { get; set; }
        public string Inserted_DocumentNumber { get; set; }
        public string Inserted_RelatedDocumentNumber { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public string Reason { get; set; }
    }
}
