//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnChart
    {
        public string Chart_of_Account_Code { get; set; }
        public string Description { get; set; }
        public string TrnCode { get; set; }
        public string TransactionCode { get; set; }
        public string DocumentType { get; set; }
        public string FormofPaymentType { get; set; }
        public string AccountCode { get; set; }
        public string CR { get; set; }
        public string Dr { get; set; }
    }
}
