//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usage_Audit
    {
        public System.Guid HdrGuid { get; set; }
        public string DossierNo { get; set; }
        public string TicketNo { get; set; }
        public string RelatedNo { get; set; }
        public string CouponCode { get; set; }
        public string ActualCountryOrigin { get; set; }
        public string ActualOrigin { get; set; }
        public string ActualCountryDestination { get; set; }
        public string ActualDestination { get; set; }
        public string ActualCarrier { get; set; }
        public Nullable<System.DateTime> ActualUsageDate { get; set; }
        public Nullable<decimal> FinalShare { get; set; }
        public string BillingType { get; set; }
        public string ActualFlight { get; set; }
        public string Immatriculation { get; set; }
        public string TypeDeReseau { get; set; }
        public string ModifiedBy { get; set; }
        public string StationID { get; set; }
    }
}
