//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public System.Guid UsrHistoryGuid { get; set; }
        public System.DateTime UsrHistoryDate { get; set; }
        public string UsrId { get; set; }
        public string UsrHash { get; set; }
        public string UsrSalt { get; set; }
        public string UsrStatus { get; set; }
        public byte UsrSecurityLevel { get; set; }
        public Nullable<System.DateTime> UsrPwdExpiry { get; set; }
        public string UsrAction { get; set; }
        public string UsrActionBy { get; set; }
        public Nullable<System.DateTime> UsrActionDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
