//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ApplicableSurcharge_FareComponent
    {
        public System.Guid HdrGuid { get; set; }
        public Nullable<int> FareComponent { get; set; }
        public string FC_origin { get; set; }
        public string FC_Destination { get; set; }
        public string ApplicableSurchargeCode { get; set; }
        public string ApplicableSurchargeCurrency { get; set; }
        public Nullable<decimal> ApplicableSurchargeAmount { get; set; }
    }
}
