//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ApplicabilityStatus_Summary_Dates
    {
        public string Reason { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public int SPANumber { get; set; }
        public int ASVNumber { get; set; }
        public string Failed { get; set; }
    }
}
