//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ApplicableTaxesUSD
    {
        public System.Guid RelatedDocumentGuid { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string ApplicableTaxCode { get; set; }
        public string Applicable_Currency { get; set; }
        public Nullable<decimal> Applicable_Tax_Amount { get; set; }
        public Nullable<decimal> APPLICABLE_TAX_USD { get; set; }
    }
}
