//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ApplicableTaxes
    {
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string Carrier { get; set; }
        public string DomesticInternational { get; set; }
        public string StopOverCode { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string PassengerType { get; set; }
        public Nullable<System.DateTime> FlightDepartureDate { get; set; }
        public string MappedPrimeCode { get; set; }
        public string TaxCode { get; set; }
        public string TaxCurrency { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public string BillingType { get; set; }
    }
}
