//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bki63_ItineraryDataSegment
    {
        public System.Guid UploadGuid { get; set; }
        public string SequenceNumber { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string Check_Digit { get; set; }
        public string SegmentIdentifier { get; set; }
        public string StopoverCode { get; set; }
        public string NotValidBeforeDate { get; set; }
        public string NotValidAfterDate { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string Carrier { get; set; }
        public string FlightNumber { get; set; }
        public string SoldPassengerCabin { get; set; }
        public string ReservationBookingDesignator { get; set; }
        public string FlightDate { get; set; }
        public string FlightDepartureTime { get; set; }
        public string FlightBookingStatus { get; set; }
        public string FreeBaggageAllowance { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string FrequentFlyerReference { get; set; }
        public string FareComponentPricedPassengerTypeCode { get; set; }
    }
}
