//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bkt06_TransactionHeader
    {
        public System.Guid UploadGuid { get; set; }
        public string SequenceNumber { get; set; }
        public string VendorISOCountryCode { get; set; }
        public string VendorIdentification { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionReferenceNumber { get; set; }
        public string NetReportingIndicator { get; set; }
        public string TransactionRecordCounter { get; set; }
        public string FormatIdentifier { get; set; }
        public string AuditStatusIndicator { get; set; }
        public string TicketingAirlineCodeNumber { get; set; }
        public string CommercialAgreementReference { get; set; }
        public string CustomerFileReference { get; set; }
        public string ClientIdentification { get; set; }
        public string ReportingSystemIdentifier { get; set; }
        public string SettlementAuthorisationCode { get; set; }
        public string ApprovedLocationNumericCode1 { get; set; }
        public string ApprovedLocationType1 { get; set; }
        public string ApprovedLocationNumericCode2 { get; set; }
        public string ApprovedLocationType2 { get; set; }
        public string ApprovedLocationNumericCode3 { get; set; }
        public string ApprovedLocationType3 { get; set; }
        public string DataInputStatusIndicator { get; set; }
        public string NetReportingMethodIndicator { get; set; }
        public string NetReportingCalculationType { get; set; }
        public string AutomatedRepricingEngineIndicator { get; set; }
        public string DocumentStatus { get; set; }
    }
}
