//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bar65_PassengerInformation
    {
        public System.Guid UploadGuid { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string Check_Digit { get; set; }
        public string PassengerName { get; set; }
        public string PassengerSpecificData { get; set; }
        public string DateofBirth { get; set; }
        public string PassengerTypeCode { get; set; }
    }
}
