//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bks45_RelatedDocumentInformation
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string RemittancePeriodEndingDate { get; set; }
        public string TransactionNumber { get; set; }
        public string RelatedTicketDocumentNumber { get; set; }
        public string Check_Digit { get; set; }
        public string WaiverCode { get; set; }
        public string ReasonforMemoIssuanceCode { get; set; }
        public string RelatedTicketDocumentCouponNumberIdentifier { get; set; }
        public string DateofIssueRelatedDocument { get; set; }
    }
}
