//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bct95_BillingAnalysis
    {
        public System.Guid UploadGuid { get; set; }
        public string SequenceNumber { get; set; }
        public string ProcessingDateIdentifier { get; set; }
        public string ProcessingCycleIdentifier { get; set; }
        public string OfficeCount { get; set; }
        public string GrossValueAmount { get; set; }
        public string TotalRemittanceAmount { get; set; }
        public string TotalCommissionValueAmount { get; set; }
        public string TotalTaxMiscellaneousFeeAmount { get; set; }
        public string TotalLateReportingPenalty { get; set; }
        public string TotalTaxonCommissionAmount { get; set; }
        public string CurrencyType { get; set; }
    }
}
