//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bmp71_AdditionalInformation
    {
        public System.Guid UploadGuid { get; set; }
        public string SequenceNumber { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string TicketDocumentNumberCheck_Digit { get; set; }
        public string InConnectionWithDocumentNumber { get; set; }
        public string Check_Digit { get; set; }
        public string BankExchangeRate { get; set; }
        public string MultiplePurposeDocumentOtherCharges { get; set; }
        public string MultiplePurposeDocumentEquivalentChargePaid { get; set; }
        public string MultiplePurposeDocumentTotalExchangeValue { get; set; }
        public string MultiplePurposeDocumentServiceCharge { get; set; }
        public string MultiplePurposeDocumentTotal { get; set; }
    }
}
