//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bar64_DocumentAmount
    {
        public System.Guid UploadGuid { get; set; }
        public string SequenceNumber { get; set; }
        public string DateofIssue { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string Check_Digit { get; set; }
        public string Fare { get; set; }
        public string TicketingModeIndicator { get; set; }
        public string EquivalentFarePaid { get; set; }
        public string Tax1 { get; set; }
        public string Tax2 { get; set; }
        public string Tax3 { get; set; }
        public string Total { get; set; }
        public string NeutralTicketingSystemIdentifier { get; set; }
        public string ServicingAirlineSystemProviderIdentifier { get; set; }
        public string FareCalculationModeIndicator { get; set; }
        public string BookingAgentIdentification { get; set; }
        public string BookingAgencyLocationNumber { get; set; }
        public string BookingEntityOutletType { get; set; }
        public string FareCalculationPricingIndicator { get; set; }
    }
}
