//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Bft99_FileTotals1
    {
        public System.Guid UploadGuid { get; set; }
        public string StandardMessageIdentifier { get; set; }
        public string SequenceNumber { get; set; }
        public string StandardNumericQualifier { get; set; }
        public string BSPIdentifier { get; set; }
        public string Reserved1 { get; set; }
        public string OfficeCount { get; set; }
        public Nullable<decimal> GrossValueAmount { get; set; }
        public Nullable<decimal> TotalRemittanceAmount { get; set; }
        public Nullable<decimal> TotalCommissionValueAmount { get; set; }
        public Nullable<decimal> TotalTaxMiscellaneousFeeAmount { get; set; }
        public Nullable<decimal> TotalLateReportingPenalty { get; set; }
        public string Reserved2 { get; set; }
        public Nullable<decimal> TotalTaxonCommissionAmount { get; set; }
        public string CurrencyType { get; set; }
        public string Reserved3 { get; set; }
    }
}
