//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Coupons_For_Outward_Billing_Excel
    {
        public string FareBasis { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string FareCurrency { get; set; }
        public Nullable<decimal> EquivalentFare { get; set; }
        public string PayCurrency { get; set; }
        public Nullable<decimal> ProrationSymphony { get; set; }
        public Nullable<decimal> OutBFinalShare { get; set; }
        public Nullable<int> MikeFinalShare { get; set; }
        public Nullable<System.DateTime> Lift_UsageDate { get; set; }
        public string UsageType { get; set; }
        public string OriginCityCode { get; set; }
        public string DestinationCityCode { get; set; }
        public string FareConstruction { get; set; }
        public string Carrier { get; set; }
        public string DocumentNumber { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string Conjunction { get; set; }
        public Nullable<int> BaseAmount_Cpn { get; set; }
        public Nullable<int> FareComponent { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public string BillingPeriod { get; set; }
        public string PrevMOC { get; set; }
        public string CouponStatus { get; set; }
        public Nullable<decimal> SPA { get; set; }
        public string BillingType { get; set; }
        public string EndosRestriction { get; set; }
    }
}
