//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CityCurrency
    {
        public string AirportCode { get; set; }
        public string CountryCode { get; set; }
        public string Currency { get; set; }
        public string CityCurrency { get; set; }
        public string Attachment { get; set; }
    }
}
