//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Columns
    {
        public string SchemaName { get; set; }
        public string TableName { get; set; }
        public string ObjectName { get; set; }
        public string ColumnName { get; set; }
        public string Data_Type { get; set; }
        public string Nullable { get; set; }
        public short ColumnLength { get; set; }
        public Nullable<short> Presision { get; set; }
        public int Scale { get; set; }
        public Nullable<long> ColumnOrder { get; set; }
        public byte xtype { get; set; }
    }
}
