//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DocumentSummary
    {
        public string SalesPeriod { get; set; }
        public string SalesYear { get; set; }
        public string SalesMonth { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string FCMI { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionGroup { get; set; }
        public string DocumentType { get; set; }
        public string DataSource { get; set; }
        public string IsExchange { get; set; }
        public string PaxSPC { get; set; }
        public string PaxType { get; set; }
        public string BspIdentifier { get; set; }
        public string IsoCountryCode { get; set; }
        public string ExchangeADC { get; set; }
        public bool SalesDataAvailable { get; set; }
        public string DocumentAirlineID { get; set; }
        public string OwnTicket { get; set; }
        public string International { get; set; }
        public string AgentNumericCode { get; set; }
        public string BookingAgentIdentification { get; set; }
        public string BookingAgencyLocationNumber { get; set; }
        public string BookingAgentID { get; set; }
        public string TicketingAgentID { get; set; }
        public string TrueOriginDestinationCityCodes { get; set; }
        public string FareCurrency { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string TotalCurrency { get; set; }
        public Nullable<decimal> EquivalentFare { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public string AmountCollectedCurrency { get; set; }
        public Nullable<decimal> AmountCollected { get; set; }
        public Nullable<decimal> FareCollected { get; set; }
        public Nullable<decimal> TaxCollected { get; set; }
        public Nullable<decimal> CommissionCollected { get; set; }
        public Nullable<decimal> SurchargeCollected { get; set; }
        public Nullable<decimal> TaxOnCommissionCollected { get; set; }
        public Nullable<decimal> FareCollectedUSD { get; set; }
        public Nullable<decimal> TaxCollectedUSD { get; set; }
        public Nullable<decimal> CommissionCollectedUSD { get; set; }
        public Nullable<decimal> SurchargeCollectedUSD { get; set; }
        public Nullable<decimal> TaxOnCommissionCollectedUSD { get; set; }
        public Nullable<int> Documents { get; set; }
    }
}
