//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Default_Constraints
    {
        public string TableName { get; set; }
        public string ConstraintName { get; set; }
        public string type_desc { get; set; }
        public string ColumnName { get; set; }
        public string definition { get; set; }
    }
}
