//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Document_ReportPeriod
    {
        public System.Guid UploadGuid { get; set; }
        public string TransactionNumber { get; set; }
        public string TicketDocumentNumber { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<System.DateTime> ReportPeriod { get; set; }
        public Nullable<System.DateTime> ProcessingPeriodEndingDate { get; set; }
        public string ProcessingPeriodEndingMonth { get; set; }
        public Nullable<int> Period { get; set; }
        public string ProcessingCenterIdentifier { get; set; }
        public string TransactionCode { get; set; }
    }
}
