//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EMD_Details_HOT
    {
        public System.Guid HdrGuid { get; set; }
        public string DocumentNumber { get; set; }
        public string TransactionCode { get; set; }
        public Nullable<System.Guid> EMDRelated_HdrGuid { get; set; }
        public string EMDCouponNumber { get; set; }
        public string EMDCouponValue { get; set; }
        public string EMDCouponCurrency { get; set; }
        public string EMDRelatedTicketNumber { get; set; }
        public string EMDRelatedCouponNumber { get; set; }
        public string EMDReasonforIssuanceSubCode { get; set; }
        public string EMDFeeOwnerAirlineDesignator { get; set; }
        public string EMDExcessBaggageOverAllowanceQualifier { get; set; }
        public string EMDExcessBaggageRateperUnit { get; set; }
        public string EMDExcessBaggageTotalNumberinExcess { get; set; }
        public string EMDConsumedatIssuanceIndicator { get; set; }
        public string EMDExcessBaggageCurrencyType { get; set; }
        public string ReasonforIssuanceCode { get; set; }
        public string ReasonforIssuanceDescription { get; set; }
        public string EMDRemarks { get; set; }
    }
}
