//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FileUploadStatus_Airline
    {
        public System.Guid UploadGuid { get; set; }
        public string ProcessingFileName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public string ProcessingFileType { get; set; }
        public string UserID { get; set; }
    }
}
