//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FareComponent
    {
        public System.Guid HdrGuid { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string DocumentNumber { get; set; }
        public string FC_Origin { get; set; }
        public string FC_Destination { get; set; }
        public Nullable<int> FareComponent { get; set; }
        public string FareBasisTicketDesignator { get; set; }
    }
}
