//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FareBasis_Discount
    {
        public System.Guid RelatedDocumentGuid { get; set; }
        public int CouponNumber { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string FareAndPassengerTypeCodeDiscount { get; set; }
        public string Discount { get; set; }
    }
}
