//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HOT_Header
    {
        public System.Guid UploadGuid { get; set; }
        public string ProcessingFileType { get; set; }
        public string BspIdentifier { get; set; }
        public string SaleSource { get; set; }
        public string IsoCountryCode { get; set; }
        public string TicketDocumentNumber { get; set; }
        public string TransactionCode { get; set; }
        public string BookingAgent { get; set; }
        public string SignCode { get; set; }
        public string TicketingAgent { get; set; }
        public string InConnectionWithDocumentNumber { get; set; }
        public string ProcessingDate { get; set; }
        public string Processingtime { get; set; }
        public string TransactionNumber { get; set; }
        public string LoadSortOrder { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public int Header_SequenceNumber { get; set; }
    }
}
