//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HOT_ProcessingFileName_For_FBS
    {
        public System.Guid HdrGuid { get; set; }
        public Nullable<System.Guid> UploadedRef { get; set; }
        public string TicketDocumentNumber { get; set; }
        public bool FBSFlag { get; set; }
        public bool SalesDataAvailable { get; set; }
        public Nullable<System.Guid> UploadGuid { get; set; }
        public string ProcessingFileName { get; set; }
    }
}
