//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_InwardBilling_Coupons
    {
        public string IssuingAirline { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> CpnNo { get; set; }
        public Nullable<int> CheckDigit { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public int SerialNo { get; set; }
        public int BillingAirlineCode { get; set; }
        public string SettlementMonthPeriod { get; set; }
        public Nullable<int> PeriodNo { get; set; }
        public Nullable<decimal> GrossFareValue { get; set; }
        public Nullable<decimal> TotalBilledAmount { get; set; }
        public Nullable<int> ISCRate { get; set; }
        public Nullable<decimal> ISCAmount { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
        public string MappedPrimeCode { get; set; }
        public string PassengerType { get; set; }
        public string BillingMonth { get; set; }
        public string PrevMOC { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public Nullable<decimal> SPAAmount { get; set; }
        public Nullable<decimal> ISCPercentage { get; set; }
        public string SPA_Applicability { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public string RBD { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string EndosRestriction { get; set; }
        public string FareCalculationArea { get; set; }
        public string FareCurrency { get; set; }
        public int ChargeCode { get; set; }
        public Nullable<byte> Processed { get; set; }
        public string AlreadyRejected { get; set; }
        public string SalesPeriod { get; set; }
        public string PrevMOS { get; set; }
        public System.Guid PrimeGuid { get; set; }
    }
}
