//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_InwardCheck
    {
        public string DocumentNo { get; set; }
        public int CouponNo { get; set; }
        public string SectorFROM { get; set; }
        public string SectorTO { get; set; }
        public string Currency { get; set; }
        public decimal BilledValue { get; set; }
        public Nullable<decimal> IscAmount { get; set; }
        public Nullable<decimal> OtherCommissionRate { get; set; }
        public Nullable<decimal> otherCommAmt { get; set; }
        public Nullable<decimal> UatpAmount { get; set; }
        public Nullable<decimal> HandlingFee { get; set; }
        public string CurrencyAdj { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public decimal MOSvalue { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<decimal> ProrateFactor { get; set; }
        public Nullable<decimal> ProrateValue { get; set; }
        public Nullable<decimal> Diffentials { get; set; }
        public Nullable<decimal> MOCfinalShare { get; set; }
        public Nullable<decimal> TaxesFeesCharges { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DifferenceInBilling { get; set; }
        public Nullable<decimal> DifferenceInExchange { get; set; }
        public string FareCalculationArea { get; set; }
        public System.Guid HdrGuid { get; set; }
        public Nullable<decimal> EquivalentFare { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string BillingPeriod { get; set; }
        public string Reference { get; set; }
        public string InvoiceNo { get; set; }
        public string BillingAirline { get; set; }
        public string BilledAirline { get; set; }
        public string sourceDoc { get; set; }
    }
}
