//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_InwardRejectionMemo
    {
        public int BillingAirlineCode { get; set; }
        public string InvoiceNumber { get; set; }
        public int SerialNo { get; set; }
        public Nullable<decimal> Fare_Your_Billing { get; set; }
        public Nullable<decimal> Fare_We_Accept { get; set; }
        public Nullable<decimal> Fare_Difference { get; set; }
        public Nullable<int> ISC__Your_Billing { get; set; }
        public Nullable<decimal> ISC__We_Accept { get; set; }
        public Nullable<decimal> ISC__Difference { get; set; }
        public Nullable<decimal> ISC_Your_Billing { get; set; }
        public Nullable<decimal> ISC_We_Accept { get; set; }
        public Nullable<decimal> ISC_Difference { get; set; }
        public Nullable<double> TFC_Your_Billing { get; set; }
        public Nullable<double> TFC_We_Accept { get; set; }
        public Nullable<double> TFC_Difference { get; set; }
        public Nullable<double> Total_Rejection { get; set; }
        public string Reason_For_Rejection { get; set; }
        public string Additional_Remarks { get; set; }
    }
}
