//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_It0A_MiscellaneousDocument
    {
        public string DocumentNumber { get; set; }
        public string MiscItem { get; set; }
        public int IsCatering { get; set; }
        public string SSRGroup { get; set; }
        public Nullable<int> TotalMiscAmount { get; set; }
        public Nullable<int> MiscItemCount { get; set; }
    }
}
