//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_inwardBills
    {
        public string InvoiceNo { get; set; }
        public string BilledAirline { get; set; }
        public string BillingAirline { get; set; }
        public string BillingPeriod { get; set; }
        public string DocumentNo { get; set; }
        public int CouponNo { get; set; }
        public string SectorFROM { get; set; }
        public string SectorTO { get; set; }
        public string Currency { get; set; }
        public decimal GrosssFare { get; set; }
        public Nullable<decimal> IscRate { get; set; }
        public Nullable<decimal> IscAmount { get; set; }
        public Nullable<decimal> OtherCommissionRate { get; set; }
        public Nullable<decimal> otherCommAmt { get; set; }
        public Nullable<decimal> UatpRate { get; set; }
        public Nullable<decimal> UatpAmount { get; set; }
        public Nullable<decimal> HandlingFee { get; set; }
        public string CurrencyAdj { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public decimal CouponValue { get; set; }
        public string AirlineName { get; set; }
        public string AirlineId { get; set; }
    }
}
