//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LiftHeader_Doublon
    {
        public string AirlineCode { get; set; }
        public string TicketNumber { get; set; }
        public string CouponNumber { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
