//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LiftCouponToPax
    {
        public Nullable<System.Guid> RelatedDocumentGuid { get; set; }
        public Nullable<int> CouponNumber { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string Carrier { get; set; }
        public string StopOverCode { get; set; }
        public string FareBasisTicketDesignator { get; set; }
        public string FlightNumber { get; set; }
        public string ReservationBookingDesignator { get; set; }
        public string FlightBookingStatus { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string UsageFlightNumber { get; set; }
        public string UsageOriginCode { get; set; }
        public string UsageDestinationCode { get; set; }
        public string UsedClassofService { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public string CouponStatus { get; set; }
        public string AccountingStatus { get; set; }
        public Nullable<bool> AccountingOnEstimate { get; set; }
        public Nullable<System.Guid> HdrGuidRef { get; set; }
        public string DocumentNumber { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public string BillingType { get; set; }
        public string DomesticInternational { get; set; }
        public string OriginCity { get; set; }
        public string DestinationCity { get; set; }
        public string OriginCountry { get; set; }
        public string DestinationCountry { get; set; }
        public string IsOAL { get; set; }
    }
}
