//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LiftForTransportation_ForTax
    {
        public string AirlineCode { get; set; }
        public string TicketNumber { get; set; }
        public string CK_Digit { get; set; }
        public Nullable<System.DateTime> FlightDepartureDate { get; set; }
        public string AgentNumericCode { get; set; }
        public int CouponNumber { get; set; }
        public string UsageOriginCode { get; set; }
        public string UsageDestinationCode { get; set; }
        public string UsageFlightNumber { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string currency { get; set; }
        public string UsedClassofService { get; set; }
        public decimal grossValue { get; set; }
        public Nullable<decimal> CommRate { get; set; }
        public Nullable<decimal> comm { get; set; }
        public decimal uatpAmount { get; set; }
        public string Htype { get; set; }
        public int handlingFee { get; set; }
        public Nullable<decimal> totalTax { get; set; }
        public string vatID { get; set; }
        public int VatAmount { get; set; }
        public string AIO { get; set; }
        public string SourceCode { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public string DocType { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<System.DateTime> FormalDate { get; set; }
    }
}
