//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Lifted_Coupon_Validation
    {
        public string AirlineCode { get; set; }
        public string UsageType { get; set; }
        public string UsageFlightNumber { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string DocumentType { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int OtherCount { get; set; }
        public string OB { get; set; }
        public string BILLINGPERIOD { get; set; }
        public string OwnTicket { get; set; }
        public string INVOICENO { get; set; }
    }
}
