//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_missing_coupons_in_source_data
    {
        public string ProcessingFileName { get; set; }
        public string DocumentNumber { get; set; }
        public string FareCalculationArea { get; set; }
        public string CouponNumber { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Comment { get; set; }
    }
}
