//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Match
    {
        public string Filename { get; set; }
        public Nullable<long> HEADERPNLID { get; set; }
        public long PNLID { get; set; }
        public Nullable<double> ID { get; set; }
        public string pnl_name { get; set; }
        public string PassengerName { get; set; }
        public int Match { get; set; }
        public string TicketNumber { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string FlightDate { get; set; }
        public string FlightDepartureDate { get; set; }
        public string FlightNo { get; set; }
        public string FlightNumber { get; set; }
        public string SectorFrom { get; set; }
        public string OriginAirportCityCode { get; set; }
        public string SectorTo { get; set; }
        public string DestinationAirportCityCode { get; set; }
        public string Status { get; set; }
    }
}
