//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OutwardVATpicker
    {
        public string ALC { get; set; }
        public Nullable<decimal> tktAmount { get; set; }
        public string INVOICENO { get; set; }
        public string BILLINGPERIOD { get; set; }
        public string DOC { get; set; }
        public string CPN { get; set; }
    }
}
