//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OutwardBilling_Base
    {
        public Nullable<int> BILLINGPERIOD { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public string AirlineID { get; set; }
        public string CPN { get; set; }
        public string RBD { get; set; }
        public string ORI { get; set; }
        public string DES { get; set; }
        public string CpnStatus { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string PM { get; set; }
        public string SPA_REMARKS { get; set; }
        public Nullable<decimal> SPA { get; set; }
        public string SPA_Currency { get; set; }
        public Nullable<decimal> FinalShare { get; set; }
        public string Proration_Error_MSG { get; set; }
        public string FCA { get; set; }
        public System.Guid RelatedDocumentGuid { get; set; }
        public string FareBasis { get; set; }
        public System.Guid HdrGuidRef { get; set; }
        public string Carrier { get; set; }
        public string UsageAirline { get; set; }
        public string DocumentNumber { get; set; }
        public decimal IscPercent { get; set; }
        public string FlightNumber { get; set; }
        public string ETKTSAC { get; set; }
        public Nullable<decimal> MinSectorVal { get; set; }
        public Nullable<decimal> MaxSectorVal { get; set; }
        public string Remarks { get; set; }
    }
}
