//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PSR
    {
        public string SaleSource { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string AgentNumericCode { get; set; }
        public string TrnKey { get; set; }
        public string TransactionCode { get; set; }
        public string ITBT { get; set; }
        public string TransactionType { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> COBL { get; set; }
        public Nullable<decimal> TMFA { get; set; }
        public Nullable<decimal> TDAM { get; set; }
        public Nullable<decimal> EFCO { get; set; }
        public Nullable<decimal> TOCA { get; set; }
        public Nullable<decimal> REMT { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
