//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProrationDetail
    {
        public System.Guid RelatedDocumentGuid { get; set; }
        public string DocumentNumber { get; set; }
        public string RelatedDocumentNumber { get; set; }
        public int CouponNumber { get; set; }
        public string Carrier { get; set; }
        public Nullable<int> FareComponent { get; set; }
        public Nullable<decimal> finalshare { get; set; }
        public Nullable<decimal> IscPercent { get; set; }
        public Nullable<decimal> UatpAmount { get; set; }
        public Nullable<decimal> SpecialProrateAgreement { get; set; }
        public Nullable<decimal> YQ { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
    }
}
