//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SalesDocumentHeader_PNL
    {
        public Nullable<System.Guid> HdrGuid { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<long> CheckDigit { get; set; }
        public System.Guid UploadedRef { get; set; }
        public string AgentNumericCode { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string PassengerName { get; set; }
        public Nullable<int> PassengerSpecificData { get; set; }
        public string FareCalculationArea { get; set; }
        public string EndosRestriction { get; set; }
        public Nullable<int> OriginalIssueInformation { get; set; }
        public Nullable<int> OriginalIssueDocumentNumber { get; set; }
        public Nullable<int> OriginalIssueCity { get; set; }
        public Nullable<System.DateTime> OriginalIssueDate { get; set; }
        public Nullable<int> OriginalIssueAgentNumericCode { get; set; }
        public Nullable<int> InConnectionWithDocumentNumber { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string FareCurrency { get; set; }
        public Nullable<decimal> EquivalentFare { get; set; }
        public Nullable<int> Tax1Currency { get; set; }
        public Nullable<int> Tax2Currency { get; set; }
        public Nullable<int> Tax3Currency { get; set; }
        public Nullable<int> Tax1Code { get; set; }
        public Nullable<int> Tax2Code { get; set; }
        public Nullable<int> Tax3Code { get; set; }
        public Nullable<int> Tax1Amount { get; set; }
        public Nullable<int> Tax2Amount { get; set; }
        public Nullable<int> Tax3Amount { get; set; }
        public string TotalCurrency { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string SequenceNumber { get; set; }
        public Nullable<int> ITBT { get; set; }
        public Nullable<int> ExchangeADC { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> TicketingModeIndicator { get; set; }
        public string FareCalculationModeIndicator { get; set; }
        public Nullable<int> BookingAgentIdentification { get; set; }
        public Nullable<int> BookingAgencyLocationNumber { get; set; }
        public Nullable<int> BookingEntityOutletType { get; set; }
        public string BookingReference { get; set; }
        public Nullable<int> AuditStatusIndicator { get; set; }
        public Nullable<int> ClientIdentification { get; set; }
        public Nullable<int> CommercialAgreementReference { get; set; }
        public Nullable<int> CustomerFileReference { get; set; }
        public Nullable<int> DataInputStatusIndicator { get; set; }
        public Nullable<int> FareCalculationPricingIndicator { get; set; }
        public Nullable<int> FormatIdentifier { get; set; }
        public Nullable<int> TourCode { get; set; }
        public Nullable<int> NetReportingIndicator { get; set; }
        public Nullable<int> NeutralTicketingSystemIdentifier { get; set; }
        public Nullable<int> ReportingSystemIdentifier { get; set; }
        public Nullable<int> ServicingAirlineSystemProviderIdentifier { get; set; }
        public string TrueOriginDestinationCityCodes { get; set; }
        public string SettlementAuthorizationCode { get; set; }
        public Nullable<int> VendorIdentification { get; set; }
        public Nullable<int> VendorISOCountryCode { get; set; }
        public string TransactionCode { get; set; }
        public int SalesDataAvailable { get; set; }
        public int AccountingStatus { get; set; }
        public int ProratedFlag { get; set; }
        public int FBSFlag { get; set; }
        public Nullable<int> DocumentAirlineID { get; set; }
        public Nullable<int> TransactionGroup { get; set; }
        public Nullable<int> PaxSPC { get; set; }
        public Nullable<int> PaxType { get; set; }
        public Nullable<int> SalesPeriod { get; set; }
        public Nullable<int> PrevMOS { get; set; }
        public Nullable<int> TotalTax { get; set; }
        public Nullable<int> TaxCurrency { get; set; }
        public Nullable<int> PayCurrency { get; set; }
        public Nullable<int> BookingAgentID { get; set; }
        public Nullable<int> TicketingAgentID { get; set; }
        public Nullable<int> IsReissue { get; set; }
        public Nullable<int> DataSource { get; set; }
        public Nullable<int> ProcessingFileType { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public Nullable<int> OwnTicket { get; set; }
        public Nullable<int> OwnCarrier { get; set; }
        public Nullable<int> OwnISOCountry { get; set; }
        public Nullable<int> OwnAirline { get; set; }
        public Nullable<int> HostCurrency { get; set; }
        public Nullable<int> AmountCollected { get; set; }
        public Nullable<int> AmountCollectedCurrency { get; set; }
        public Nullable<int> TaxCollected { get; set; }
        public Nullable<int> TaxCollectedCurrency { get; set; }
        public Nullable<int> SurchargeCollected { get; set; }
        public Nullable<int> SurchargeCollectedCurrency { get; set; }
        public Nullable<int> CommissionCollected { get; set; }
        public Nullable<int> CommissionCollectedCurrency { get; set; }
        public Nullable<int> BilateralEndorsement { get; set; }
        public Nullable<int> InvoluntaryReroute { get; set; }
        public Nullable<int> BspIdentifier { get; set; }
        public Nullable<int> IsoCountryCode { get; set; }
        public Nullable<int> USDRatePayCur { get; set; }
        public Nullable<int> USDRateHostCur { get; set; }
        public Nullable<int> PMPPeriod { get; set; }
        public Nullable<int> TaxOnCommissionCollected { get; set; }
        public Nullable<int> TaxOnCommissionCollectedCurrency { get; set; }
        public Nullable<int> SignCode { get; set; }
    }
}
