//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SD_PaxAmountsConverted
    {
        public System.Guid HdrGuid { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string TransactionCode { get; set; }
        public string OriginalIssueDocumentNumber { get; set; }
        public string ExchangeADC { get; set; }
        public int EX { get; set; }
        public string Fare_ { get; set; }
        public string EquivalentFare_ { get; set; }
        public string FareOrEquivFare_ { get; set; }
        public string Fare_Tax { get; set; }
        public string TotalAmount_ { get; set; }
        public string AmountCollected_ { get; set; }
        public string FareCollected_ { get; set; }
        public string FareCurrency { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public string TotalCurrency { get; set; }
        public Nullable<decimal> EquivalentFare { get; set; }
        public string AmountCollectedCurrency { get; set; }
        public Nullable<decimal> FareCollected { get; set; }
        public Nullable<decimal> CommissionCollected { get; set; }
        public Nullable<decimal> TaxOnCommissionCollected { get; set; }
        public Nullable<decimal> TaxCollected { get; set; }
        public Nullable<decimal> SurchargeCollected { get; set; }
        public Nullable<decimal> FareCollectedUSD { get; set; }
        public Nullable<decimal> FareUSD { get; set; }
        public Nullable<decimal> AmountCollectedUSD { get; set; }
        public Nullable<decimal> CommissionCollectedUSD { get; set; }
        public Nullable<decimal> TaxOnCommissionCollectedUSD { get; set; }
        public Nullable<decimal> TaxCollectedUSD { get; set; }
        public Nullable<decimal> SurchargeCollectedUSD { get; set; }
        public Nullable<decimal> FareCollectedSDG { get; set; }
        public Nullable<decimal> FareSDG { get; set; }
        public Nullable<decimal> AmountCollectedSDG { get; set; }
        public Nullable<decimal> CommissionCollectedSDG { get; set; }
        public Nullable<decimal> TaxOnCommissionCollectedSDG { get; set; }
        public Nullable<decimal> TaxCollectedSDG { get; set; }
        public Nullable<decimal> SurchargeCollectedSDG { get; set; }
        public Nullable<decimal> USDRateHostCur { get; set; }
        public Nullable<decimal> USDRatePayCur { get; set; }
    }
}
