//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SalesComponent
    {
        public string SalesPeriod { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string DocumentNumber { get; set; }
        public string AgentNumericCode { get; set; }
        public string Currency { get; set; }
        public string FormofPaymentType { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionGroup { get; set; }
        public string Component { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
