//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Ticket_Accounting
    {
        public string OriginalIssue { get; set; }
        public string DocumentNumber { get; set; }
        public string TransactionCode { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string Ex { get; set; }
        public string ExchangeADC { get; set; }
        public string OUTWARD_BILLING { get; set; }
        public string OUTWARD_BILLING_ISC { get; set; }
        public string OUTWARD_BILLING_NET { get; set; }
        public string OUTWARD_BILLING_TAX { get; set; }
        public string OUTWARD_BILLING_TOTAL { get; set; }
        public string INWARD_BILLING { get; set; }
        public string INWARD_BILLING_ISC { get; set; }
        public string INWARD_BILLING_TAX { get; set; }
        public string INWARD_BILLING_TOTAL { get; set; }
        public string BANK_ACC { get; set; }
        public string FORWARD_SALES_ACC { get; set; }
        public string TFCs_SUSPENSE { get; set; }
        public string FLOWN_REVENUE { get; set; }
        public string INTERLINE_FLOWN_REVENUE { get; set; }
        public string ACC_PAYABLE { get; set; }
        public string ISC_PAYABLE { get; set; }
        public string TAX_PAYABLE { get; set; }
        public string ACC_RECEIVABLE { get; set; }
        public string ISC_RECEIVABLE { get; set; }
        public string TAX_RECEIVABLE { get; set; }
        public string SALES_COMMISSION { get; set; }
        public string EXCH_COUPON_ACC { get; set; }
        public string TFC_EXCH_ACC { get; set; }
        public string REFUND_COUP_ACC { get; set; }
        public string TFC_REFUND_ACC { get; set; }
        public Nullable<decimal> Check1 { get; set; }
    }
}
