//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataHelpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class XmlStructureIn
    {
        public long lineId { get; set; }
        public string Section { get; set; }
        public string SectionType { get; set; }
        public string SubGroup1 { get; set; }
        public string SubGroup2 { get; set; }
        public string SubGroup3 { get; set; }
        public string SubGroup4 { get; set; }
        public string FieldName { get; set; }
        public string DataValue { get; set; }
        public string FieldType { get; set; }
        public string FieldSize { get; set; }
        public Nullable<int> FieldID { get; set; }
        public string SourceData { get; set; }
        public string NormaliseTableName { get; set; }
        public string DataSourceRef { get; set; }
    }
}
